'use client';

import { useEffect, useMemo, useState } from 'react';
import { Capacitor } from '@capacitor/core';
import { StatusBar, Style } from '@capacitor/status-bar';
import { App as CapacitorApp } from '@capacitor/app';
import supabase from '../lib/supabase';
import { hitungXpEarned, levelFromXp, levelProgress, titleForLevel } from '../lib/xp';
import { nextStreak } from '../lib/streak';
import { badgeStats, evaluateBadges, FALLBACK_BADGE_DEFS } from '../lib/badges';
import { drawProfileCard } from '../lib/profileCard';
import { addDays, generateDue, occurrenceOnOrAfter } from '../lib/recurring';
import { buildRecap } from '../lib/recap';
import { buildAdvice } from '../lib/advice';
import { CURRENCIES, isStale, loadCachedFx, makeMoneyFormatter, refreshFxCache } from '../lib/fx';
import { LANGS, getLang, setLang, t } from '../lib/i18n';
import { csvToTransactions, dupKeyOf, transactionsToCsv } from '../lib/csv';
import { exportPdf } from '../lib/reportPdf';
import { fireTestPing, reminderPermissionState, requestReminderPermission, syncReminders } from '../lib/reminders';
import LevelUpModal from './LevelUpModal';

const dateFormatterCache = {};
function dateFmt() {
  const locale = getLang() === 'en' ? 'en-US' : 'id-ID';
  return dateFormatterCache[locale] ?? (dateFormatterCache[locale] = new Intl.DateTimeFormat(locale, { day: 'numeric', month: 'short', year: 'numeric' }));
}
const today = new Date().toISOString().slice(0, 10);

const initialData = { users: [], transactions: {}, goals: {}, achievements: {}, budgets: {}, badges: {}, badgeDefs: [], categories: {}, recurrings: {}, activeUserId: null };
/* Seed kategori default (is_default) — dipakai saat user belum punya baris di tabel categories.
   Lainnya bertipe 'both' supaya muncul di dropdown pemasukan & pengeluaran. */
const DEFAULT_CATEGORIES = [
  ['Makan & Minum', '🍜', 'expense'],
  ['Transportasi', '🛵', 'expense'],
  ['Belanja', '🛍️', 'expense'],
  ['Tagihan', '🧾', 'expense'],
  ['Hiburan', '🎮', 'expense'],
  ['Gaji', '💼', 'income'],
  ['Bonus', '🎉', 'income'],
  ['Usaha', '🏪', 'income'],
  ['Investasi', '📈', 'income'],
  ['Lainnya', '✨', 'both'],
];
const NAV_TABS = [['beranda', '🏠'], ['transaksi', '💸'], ['target', '🎯'], ['profil', '👤']];
/* Restrukturisasi Profil: baris menu utama (sub-halaman pengingat kondisional & danger ditangani terpisah di JSX) */
const PROFILE_MENU_ROWS = [
  ['kartu', '🪪', 'prof.menu.kartu'],
  ['pengaturan', '⚙️', 'prof.menu.pengaturan'],
  ['kategori', '🗂️', 'cat.title'],
  ['rutin', '🔁', 'recM.title'],
  ['data', '📦', 'data.title'],
  ['saran', '💡', 'prof.menu.saran'],
];
const MASKED_AMOUNT = 'Rp ••••••';

function mapTransaction(row) {
  return { id: row.id, type: row.type, title: row.title, amount: Number(row.amount), category: row.category, date: row.date, xp_earned: row.xp_earned ?? 0 };
}

function mapCategory(row) {
  return { id: row.id, name: row.name, emoji: row.emoji, type: row.type, isDefault: Boolean(row.is_default) };
}

function mapRecurring(row) {
  return { id: row.id, type: row.type, title: row.title, amount: Number(row.amount), category: row.category, frequency: row.frequency, dayOfPeriod: row.day_of_period, nextRunDate: row.next_run_date };
}

async function loadData(userId) {
  const [trx, goal, ach, bud, defs, owned, cats, recs] = await Promise.all([
    supabase.from('transactions').select('*').eq('user_id', userId),
    supabase.from('goals').select('*').eq('user_id', userId).eq('is_active', true).maybeSingle(),
    supabase.from('achievements').select('*').eq('user_id', userId),
    supabase.from('budgets').select('*').eq('user_id', userId),
    supabase.from('badge_defs').select('*'),
    supabase.from('user_badges').select('badge_code').eq('user_id', userId),
    supabase.from('categories').select('*').eq('user_id', userId).order('created_at'),
    supabase.from('recurring_transactions').select('*').eq('user_id', userId).eq('is_active', true).order('next_run_date'),
  ]);
  return {
    transactions: (trx.data ?? []).map(mapTransaction),
    goal: goal.data ? { name: goal.data.name, amount: Number(goal.data.amount) } : null,
    achievements: (ach.data ?? []).map((row) => ({ id: row.id, name: row.goal_name, amount: Number(row.goal_amount), completedAt: row.completed_at })),
    budgets: Object.fromEntries((bud.data ?? []).map((row) => [row.category, Number(row.monthly_limit)])),
    badgeDefs: (defs.data ?? []).length ? defs.data : FALLBACK_BADGE_DEFS,
    badges: (owned.data ?? []).map((row) => row.badge_code),
    categories: (cats.data ?? []).map(mapCategory),
    recurrings: (recs.data ?? []).map(mapRecurring),
  };
}

export default function Home() {
  const [data, setData] = useState(initialData);
  const [ready, setReady] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(0);
  const [fontScale, setFontScale] = useState(() => (typeof window !== 'undefined' && window.localStorage.getItem('rapi.fontScale')) || '1');
  const [lang, setLangState] = useState(() => (typeof window !== 'undefined' && window.localStorage.getItem('rapi.lang')) || 'id');
  const [theme, setTheme] = useState(() => (typeof window !== 'undefined' && window.localStorage.getItem('rapi.theme')) || 'system');
  setLang(lang);
  useEffect(() => {
    document.documentElement.style.setProperty('--font-scale', fontScale);
    return () => {};
  }, [fontScale]);
  /* Tema: 'system' mengikuti prefers-color-scheme (atribut data-theme dibersihkan),
     'light'/'dark' menulis [data-theme] di <html> — CSS brutal sudah siap dua-duanya. */
  useEffect(() => {
    const root = document.documentElement;
    const mq = window.matchMedia('(prefers-color-scheme: dark)');
    const apply = () => {
      if (theme === 'system') root.removeAttribute('data-theme');
      else root.dataset.theme = theme;
      /* Ikon status bar kontras dengan tema efektif (terang teks saat gelap) */
      if (Capacitor.isNativePlatform()) {
        const darkNow = theme === 'dark' || (theme === 'system' && mq.matches);
        StatusBar.setStyle({ style: darkNow ? Style.Dark : Style.Light }).catch(() => {});
      }
    };
    apply();
    mq.addEventListener('change', apply);
    return () => mq.removeEventListener('change', apply);
  }, [theme]);
  /* Sinkronkan atribut <html lang> & tab title dengan bahasa aktif (aksesibilitas + PWA) */
  useEffect(() => {
    document.documentElement.lang = lang;
    document.title = t('meta.title');
    return () => {};
  }, [lang]);
  function changeLanguage(next) {
    setLangState(next);
    try { window.localStorage.setItem('rapi.lang', next); } catch {}
  }
  function changeFontScale(value) {
    setFontScale(value);
    try { window.localStorage.setItem('rapi.fontScale', value); } catch {}
  }
  function changeTheme(next) {
    setTheme(next);
    try { window.localStorage.setItem('rapi.theme', next); } catch {}
  }

  async function enterApp(authUser, fallbackName) {
    let profile = (await supabase.from('profiles').select('*').eq('id', authUser.id).maybeSingle()).data;
    if (!profile) {
      const username = fallbackName || authUser.email.replace(/@rapi\.local$/, '');
      profile = (await supabase.from('profiles').insert({ id: authUser.id, username }).select().single()).data
        ?? { id: authUser.id, username, xp: 0, level: 1 };
    }
    const snapshot = await loadData(authUser.id);
    let categories = snapshot.categories;
    if (!categories.length) {
      const { data: seeded, error } = await supabase.from('categories')
        .upsert(
          DEFAULT_CATEGORIES.map(([name, emoji, type]) => ({ user_id: authUser.id, name, emoji, type, is_default: true })),
          { onConflict: 'user_id,name' },
        )
        .select();
      if (!error && seeded?.length) categories = seeded.map(mapCategory);
    }
    let recurrings = snapshot.recurrings;
    let autoCount = 0;
    try {
      const { rows, updates, generated } = generateDue(recurrings, today);
      if (rows.length) {
        const { error } = await supabase.from('transactions').insert(rows.map((row) => ({ ...row, user_id: authUser.id, xp_earned: 0 })));
        if (!error) {
          autoCount = generated;
          await Promise.all(updates.map((item) => supabase.from('recurring_transactions').update({ next_run_date: item.nextRunDate }).eq('id', item.id)));
          recurrings = recurrings.map((rule) => {
            const update = updates.find((item) => item.id === rule.id);
            return update ? { ...rule, nextRunDate: update.nextRunDate } : rule;
          });
        }
      }
    } catch {}
    setAutoGenerated(autoCount);
    if (typeof window !== 'undefined' && window.localStorage.getItem('rapi.reminder.enabled') === '1') {
      const reminderHour = Number(window.localStorage.getItem('rapi.reminder.hour')) || 20;
      await syncReminders({ enabled: true, hour: reminderHour, recurrings, lang });
    }
    const account = { id: authUser.id, username: profile.username, xp: profile.xp ?? 0, level: profile.level ?? 1, streakCurrent: profile.streak_current ?? 0, streakLongest: profile.streak_longest ?? 0 };
    setData((current) => ({
      ...current,
      users: current.users.some((user) => user.id === authUser.id)
        ? current.users.map((user) => (user.id === authUser.id ? account : user))
        : [...current.users, account],
      transactions: { ...current.transactions, [authUser.id]: snapshot.transactions },
      goals: { ...current.goals, [authUser.id]: snapshot.goal },
      achievements: { ...current.achievements, [authUser.id]: snapshot.achievements },
      budgets: { ...current.budgets, [authUser.id]: snapshot.budgets },
      badges: { ...current.badges, [authUser.id]: snapshot.badges },
      badgeDefs: snapshot.badgeDefs,
      categories: { ...current.categories, [authUser.id]: categories },
      recurrings: { ...current.recurrings, [authUser.id]: recurrings },
      activeUserId: authUser.id,
    }));
    setReady(true);
  }

  useEffect(() => {
    supabase.auth.getSession().then(async ({ data: { session } }) => {
      if (session?.user) await enterApp(session.user);
      else setReady(true);
    });
  }, []);

  const activeUser = data.users.find((user) => user.id === data.activeUserId) ?? null;
  if (!ready) return <div className="loading"><span className="loading-dot" />{t('common.loading')}</div>;

  return activeUser
    ? <Dashboard user={activeUser} data={data} setData={setData} autoGenerated={autoGenerated} fontScale={fontScale} onChangeFontScale={changeFontScale} onChangeLang={changeLanguage} lang={lang} theme={theme} onChangeTheme={changeTheme} />
    : <Auth onEnter={enterApp} />;
}

function BottomNav({ active, onChange, onAdd }) {
  const item = ([id, icon, label]) => <button key={id} type="button" className={`bottom-nav-item ${active === id ? 'active' : ''}`} aria-current={active === id ? 'page' : undefined} onClick={() => onChange(id)}><span>{icon}</span><small>{t(`nav.${id}`)}</small></button>;
  return <nav className="bottom-nav brutal-nav" aria-label={t('nav.aria')}>
    {item(NAV_TABS[0])}
    {item(NAV_TABS[1])}
    <div className="nav-fab-slot">
      <button type="button" className="nav-fab" aria-label={t('nav.fabAria')} onClick={onAdd}>+</button>
    </div>
    {item(NAV_TABS[2])}
    {item(NAV_TABS[3])}
  </nav>;
}

function Auth({ onEnter }) {
  const [mode, setMode] = useState('login');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [message, setMessage] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  async function submit(event) {
    event.preventDefault();
    if (isSubmitting) return;
    const cleanName = username.trim();
    if (cleanName.length < 3) return setMessage(t('err.nameShort'));
    if (password.length < 6) return setMessage(t('err.passShort'));

    const email = `${cleanName.toLowerCase()}@rapi.local`;
    setIsSubmitting(true);
    try {
      if (mode === 'register') {
        const { data: authData, error } = await supabase.auth.signUp({ email, password });
        if (error) {
          if (/already registered|already exists/i.test(error.message)) setMessage(t('err.nameTaken'));
          else if (error.code === 'weak_password' || /weak password|at least \d+ characters/i.test(error.message)) setMessage(t('err.passWeak'));
          else if (error.code === 'over_request_rate_limit' || /rate limit/i.test(error.message)) setMessage(t('err.rateLimit'));
          else setMessage(t('err.registerFailed', { msg: error.message }));
          return;
        }
        if (!authData.session) return setMessage(t('ok.accountCreated'));
        onEnter(authData.user, cleanName);
        return;
      }

      const { data: authData, error } = await supabase.auth.signInWithPassword({ email, password });
      if (error || !authData.user) return setMessage(t('err.badCreds'));
      onEnter(authData.user);
    } finally {
      setIsSubmitting(false);
    }
  }

  function changeMode(next) {
    setMode(next); setMessage(''); setUsername(''); setPassword('');
  }

  return <main className="auth-page clay-auth brutal-auth">
    <section className="auth-intro">
      <a className="brand dark brutal-brand" href="#top"><span>r</span> rapi</a>
      <div className="intro-copy">
        <p className="kicker">{t('auth.kicker')}</p>
        <h1>{t('auth.tagline1')}<br /><em>{t('auth.tagline2')}</em></h1>
        <p>{t('auth.desc')}</p>
      </div>
      <div className="feature-note"><span>✦</span><div><strong>{t('auth.privacyTitle')}</strong><small>{t('auth.privacyNote')}</small></div></div>
    </section>
    <section className="auth-panel" id="top">
      <div className="form-wrap clay-card brutal-card">
        <p className="welcome">{t(mode === 'login' ? 'welcome.login' : 'welcome.register')}</p>
        <h2>{t(mode === 'login' ? 'auth.titleLogin' : 'auth.titleRegister')}</h2>
        <p className="form-description">{t(mode === 'login' ? 'auth.descLogin' : 'auth.descRegister')}</p>
        <form onSubmit={submit}>
          <label>{t('label.username')}<input value={username} onChange={(e) => setUsername(e.target.value)} placeholder={t('ph.username')} autoComplete="username" /></label>
          <label>{t('label.password')}<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder={t('ph.password')} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} /></label>
          {message && <p className="form-message" role="alert">{message}</p>}
          <button className="primary-button clay-button brutal-button" type="submit" disabled={isSubmitting}>{isSubmitting ? t('btn.processing') : t(mode === 'login' ? 'btn.login' : 'btn.register')}{!isSubmitting && <span>→</span>}</button>
        </form>
        <p className="switch-form">{t(mode === 'login' ? 'switch.toRegister' : 'switch.toLogin')} <button className="brutal-switch" onClick={() => changeMode(mode === 'login' ? 'register' : 'login')}>{t(mode === 'login' ? 'btn.register' : 'btn.login')}</button></p>
        <p className="privacy">{t('privacy.demo')}</p>
      </div>
    </section>
  </main>;
}

function Dashboard({ user, data, setData, autoGenerated = 0, fontScale = '1', onChangeFontScale, onChangeLang, lang = 'id', theme = 'system', onChangeTheme }) {
  const [tab, setTab] = useState('beranda');
  const [showForm, setShowForm] = useState(false);
  const [budgetSheet, setBudgetSheet] = useState(null);
  const [goalSheet, setGoalSheet] = useState(false);
  const [categorySheet, setCategorySheet] = useState(false);
  const [recurringSheet, setRecurringSheet] = useState(false);
  const [filter, setFilter] = useState('all');
  const [levelUp, setLevelUp] = useState(null);
  const [toast, setToast] = useState('');
  const showReminderCard = Capacitor.isNativePlatform();
  const [reminderEnabled, setReminderEnabled] = useState(() => typeof window !== 'undefined' && window.localStorage.getItem('rapi.reminder.enabled') === '1');
  const [reminderHour, setReminderHour] = useState(() => Number(typeof window !== 'undefined' && window.localStorage.getItem('rapi.reminder.hour')) || 20);
  const [reminderMsg, setReminderMsg] = useState('');
  const [hideBalance, setHideBalance] = useState(() => typeof window !== 'undefined' && window.localStorage.getItem('rapi.balance.hidden') === '1');
  const [categoryFilter, setCategoryFilter] = useState('');
  const [sortMode, setSortMode] = useState('newest');
  const [recapPeriod, setRecapPeriod] = useState('week');
  const [pdfRange, setPdfRange] = useState('this');
  const [pdfCustom, setPdfCustom] = useState({ start: '', end: '' });
  const [importSheetOpen, setImportSheetOpen] = useState(false);
  const [importPreview, setImportPreview] = useState(null);
  const [importBusy, setImportBusy] = useState(false);
  const [fxCode, setFxCode] = useState(() => (typeof window !== 'undefined' && window.localStorage.getItem('rapi.currency')) || 'IDR');
  const [fxData, setFxData] = useState(() => loadCachedFx());
  const [fxStatus, setFxStatus] = useState(() => (loadCachedFx() ? 'ready' : 'idle'));
  const [profileView, setProfileView] = useState(null);
  useEffect(() => {
    let cancelled = false;
    (async () => {
      const cache = loadCachedFx();
      if (!isStale(cache)) return;
      if (!cache) setFxStatus('loading');
      const fresh = await refreshFxCache(cache);
      if (cancelled) return;
      if (fresh) {
        setFxData(fresh);
        setFxStatus('ready');
      } else {
        setFxStatus(loadCachedFx() ? 'stale' : 'unavailable');
      }
    })();
    return () => { cancelled = true; };
  }, []);
  function changeCurrency(code) {
    setFxCode(code);
    try { window.localStorage.setItem('rapi.currency', code); } catch {}
    if (code !== 'IDR' && (!fxData || isStale(fxData))) {
      setFxStatus('loading');
      refreshFxCache(fxData).then((fresh) => {
        if (fresh) {
          setFxData(fresh);
          setFxStatus('ready');
        } else {
          setFxStatus(loadCachedFx() ? 'stale' : 'unavailable');
        }
      });
    }
  }
  const money = useMemo(() => makeMoneyFormatter(fxCode, fxData?.rates), [fxCode, fxData]);
  function toggleHideBalance() {
    setHideBalance((current) => {
      const next = !current;
      try { window.localStorage.setItem('rapi.balance.hidden', next ? '1' : '0'); } catch {}
      return next;
    });
  }
  useEffect(() => {
    if (!autoGenerated) return;
    setToast(t('toast.autoLogged', { n: autoGenerated }));
    const timer = setTimeout(() => setToast(''), 4000);
    return () => clearTimeout(timer);
  }, [autoGenerated]);
  /* Sub-halaman Profil: reset saat pindah tab utama + scroll ke atas tiap ganti view */
  useEffect(() => {
    setProfileView(null);
    return () => {};
  }, [tab]);
  useEffect(() => {
    window.scrollTo(0, 0);
    return () => {};
  }, [profileView]);
  useEffect(() => {
    if (!Capacitor.isNativePlatform()) return;
    const subscription = CapacitorApp.addListener('backButton', () => {
      if (levelUp) setLevelUp(null);
      else if (showForm) setShowForm(false);
      else if (budgetSheet) setBudgetSheet(null);
      else if (goalSheet) setGoalSheet(false);
      else if (categorySheet) setCategorySheet(false);
      else if (recurringSheet) setRecurringSheet(false);
      else if (importSheetOpen) { setImportSheetOpen(false); setImportPreview(null); }
      else if (profileView) setProfileView(null);
      else if (tab !== 'beranda') setTab('beranda');
      else CapacitorApp.exitApp();
    });
    return () => subscription.remove();
  }, [tab, showForm, budgetSheet, goalSheet, categorySheet, recurringSheet, importSheetOpen, levelUp, profileView]);
  const transactions = data.transactions[user.id] ?? [];
  const sortedTransactions = useMemo(() => [...transactions].sort((a, b) => new Date(b.date) - new Date(a.date)), [transactions]);
  const visibleTransactions = useMemo(() => {
    const byType = filter === 'all' ? sortedTransactions : sortedTransactions.filter((item) => item.type === filter);
    const byCategory = categoryFilter ? byType.filter((item) => item.category === categoryFilter) : byType;
    return sortMode === 'amount' ? [...byCategory].sort((a, b) => b.amount - a.amount) : byCategory;
  }, [sortedTransactions, filter, categoryFilter, sortMode]);
  const income = transactions.filter((item) => item.type === 'income').reduce((sum, item) => sum + item.amount, 0);
  const expense = transactions.filter((item) => item.type === 'expense').reduce((sum, item) => sum + item.amount, 0);
  const balance = income - expense;
  const goal = data.goals?.[user.id] ?? null;
  const achievements = data.achievements?.[user.id] ?? [];
  const goalReached = Boolean(goal && balance >= goal.amount);
  const budgets = data.budgets?.[user.id] ?? {};
  const categories = data.categories?.[user.id] ?? [];
  const recurrings = data.recurrings?.[user.id] ?? [];
  const expenseCategories = useMemo(() => categories.filter((item) => item.type !== 'income').map((item) => item.name), [categories]);
  const incomeCategories = useMemo(() => categories.filter((item) => item.type !== 'expense').map((item) => item.name), [categories]);
  const emojiMap = useMemo(() => Object.fromEntries(categories.map((item) => [item.name, item.emoji])), [categories]);
  const categoryChips = useMemo(() => {
    const counts = {};
    for (const item of transactions) if (item.category) counts[item.category] = (counts[item.category] ?? 0) + 1;
    return [...categories].sort((a, b) => ((counts[b.name] ?? 0) - (counts[a.name] ?? 0)) || a.name.localeCompare(b.name, 'id'));
  }, [categories, transactions]);
  const monthKey = today.slice(0, 7);
  const monthExpenses = transactions.filter((item) => item.type === 'expense' && item.date.startsWith(monthKey));
  const budgetEntries = Object.entries(budgets);
  const spendingFor = (category) => monthExpenses.filter((item) => item.category === category).reduce((sum, item) => sum + item.amount, 0);
  const categorySummary = expenseCategories.map((category) => ({ category, amount: spendingFor(category) })).filter((item) => item.amount > 0).sort((a, b) => b.amount - a.amount);
  const topSpending = categorySummary[0];
  const chartMax = topSpending?.amount || 1;
  const badgeViews = evaluateBadges(
    data.badgeDefs?.length ? data.badgeDefs : FALLBACK_BADGE_DEFS,
    badgeStats({ transactions, achievements, streakCurrent: user.streakCurrent, level: user.level }),
    new Set(data.badges?.[user.id] ?? []),
    lang,
  );
  const unlockedBadges = badgeViews.filter((badge) => badge.unlocked).length;
  const topCardTier = ['legendary', 'epic', 'rare', 'common'].find((tier) => badgeViews.some((badge) => badge.unlocked && badge.rarity === tier)) ?? 'common';
  const canShareCard = typeof navigator !== 'undefined' && Boolean(navigator.canShare);
  const profInfo = levelProgress(user.xp ?? 0, lang);
  const recap = useMemo(() => buildRecap({ transactions, period: recapPeriod, streak: user.streakCurrent ?? 0, money, lang }), [transactions, recapPeriod, user.streakCurrent, money, lang]);
  /* F1 — saran finansial: engine rule-based deterministik (lib/advice.js). */
  const advice = useMemo(() => buildAdvice({
    transactions, budgets, goal, recurrings, lang, money, today,
    emojiOf: (name) => emojiMap[name] ?? '✨',
  }), [transactions, budgets, goal, recurrings, lang, money, emojiMap]);
  const adviceHigh = advice.items.filter((item) => item.severity === 'tinggi');

  useEffect(() => {
    const owned = new Set(data.badges?.[user.id] ?? []);
    const fresh = badgeViews.filter((badge) => badge.unlocked && !owned.has(badge.code));
    if (!fresh.length) return;
    supabase.from('user_badges').insert(fresh.map((badge) => ({ user_id: user.id, badge_code: badge.code }))).then(({ error }) => {
      if (error) return;
      setData((current) => ({ ...current, badges: { ...current.badges, [user.id]: [...(current.badges[user.id] ?? []), ...fresh.map((badge) => badge.code)] } }));
    });
  }, [badgeViews]);

  async function addTransaction(transaction) {
    const xpEarned = hitungXpEarned(transaction, transactions, budgets);
    const previousLevel = user.level ?? 1;
    const totalXp = (user.xp ?? 0) + xpEarned;
    const newLevel = levelFromXp(totalXp);
    const { data: inserted, error } = await supabase
      .from('transactions')
      .insert({ user_id: user.id, type: transaction.type, title: transaction.title, amount: transaction.amount, category: transaction.category, date: transaction.date, xp_earned: xpEarned })
      .select()
      .single();
    if (error || !inserted) return false;
    let streakInfo = null;
    try {
      const { data: prof } = await supabase.from('profiles').select('streak_current, streak_longest, last_activity_date').eq('id', user.id).single();
      streakInfo = nextStreak(prof?.last_activity_date, prof?.streak_current, prof?.streak_longest);
      await supabase.from('profiles').update({ streak_current: streakInfo.streakCurrent, streak_longest: streakInfo.streakLongest, last_activity_date: streakInfo.today }).eq('id', user.id);
    } catch {
      streakInfo = null;
    }
    setData((current) => ({
      ...current,
      transactions: { ...current.transactions, [user.id]: [mapTransaction(inserted), ...(current.transactions[user.id] ?? [])] },
      users: current.users.map((item) => (item.id === user.id ? { ...item, xp: totalXp, level: newLevel, ...(streakInfo ? { streakCurrent: streakInfo.streakCurrent, streakLongest: streakInfo.streakLongest } : {}) } : item)),
    }));
    setShowForm(false);
    if (newLevel > previousLevel) setLevelUp({ level: newLevel, xpEarned });
    return true;
  }
  async function removeTransaction(id) {
    const { error } = await supabase.from('transactions').delete().eq('id', id);
    if (error) return;
    setData((current) => ({ ...current, transactions: { ...current.transactions, [user.id]: (current.transactions[user.id] ?? []).filter((item) => item.id !== id) } }));
  }
  function pdfRangeDates() {
    if (pdfRange === 'this') return { start: `${today.slice(0, 7)}-01`, end: today };
    if (pdfRange === 'last') {
      const [y, m] = today.split('-').map(Number);
      const py = m === 1 ? y - 1 : y;
      const pm = m === 1 ? 12 : m - 1;
      return { start: `${py}-${String(pm).padStart(2, '0')}-01`, end: `${py}-${String(pm).padStart(2, '0')}-${new Date(py, pm, 0).getDate()}` };
    }
    if (!pdfCustom.start || !pdfCustom.end || pdfCustom.start > pdfCustom.end) return null;
    return { start: pdfCustom.start, end: pdfCustom.end };
  }
  async function handleExportPdf() {
    const range = pdfRangeDates();
    if (!range) { setToast(t('toast.customRange')); return; }
    const scoped = transactions.filter((tx) => tx.date >= range.start && tx.date <= range.end);
    if (!scoped.length) { setToast(t('toast.rangeEmpty')); return; }
    const label = pdfRange === 'this' ? t('pdf.thisMonth') : pdfRange === 'last' ? t('pdf.lastMonth') : `${range.start} ${t('pdf.to')} ${range.end}`;
    try {
      await exportPdf({ transactions: scoped, rangeLabel: label, fileName: `rapi-laporan-${range.start}`, lang });
      setToast(t('toast.pdfDone'));
    } catch { setToast(t('toast.pdfFail')); }
  }
  function handleExportCsv() {
    if (!transactions.length) { setToast(t('toast.noExportData')); return; }
    const blob = new Blob([transactionsToCsv(transactions)], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'rapi-transaksi.csv';
    link.click();
    URL.revokeObjectURL(url);
    setToast(t('toast.csvDone'));
  }
  async function handleImportFile(event) {
    const file = event.target.files?.[0];
    event.target.value = '';
    if (!file) return;
    if (file.size > 5 * 1024 * 1024) { setToast(t('toast.fileTooBig')); return; }
    let text;
    try { text = await file.text(); } catch { setToast(t('toast.fileUnreadable')); return; }
    setImportPreview({ fileName: file.name, result: csvToTransactions(text, new Set(transactions.map(dupKeyOf)), lang) });
  }
  async function confirmImport() {
    const rows = importPreview?.result?.valid ?? [];
    if (!rows.length || importBusy) return;
    setImportBusy(true);
    try {
      const known = new Set(categories.map((item) => item.name));
      const newNames = new Map();
      for (const row of rows) if (!known.has(row.category) && !newNames.has(row.category)) newNames.set(row.category, row.type);
      let createdCategories = [];
      if (newNames.size) {
        const payload = [...newNames.entries()].map(([name, type]) => ({ user_id: user.id, name, emoji: '📦', type }));
        const { data: seeded } = await supabase.from('categories').upsert(payload, { onConflict: 'user_id,name' }).select();
        if (seeded) createdCategories = seeded.map(mapCategory);
      }
      const inserted = [];
      for (let i = 0; i < rows.length; i += 200) {
        const chunk = rows.slice(i, i + 200).map((row) => ({ user_id: user.id, type: row.type, title: row.title, amount: row.amount, category: row.category, date: row.date, xp_earned: 0 }));
        const { data, error } = await supabase.from('transactions').insert(chunk).select();
        if (error) throw error;
        inserted.push(...data.map(mapTransaction));
      }
      setData((current) => ({
        ...current,
        categories: { ...current.categories, [user.id]: [...(current.categories[user.id] ?? []), ...createdCategories] },
        transactions: { ...current.transactions, [user.id]: [...inserted, ...(current.transactions[user.id] ?? [])] },
      }));
      setImportSheetOpen(false);
      setImportPreview(null);
      setToast(t('toast.imported', { n: inserted.length }));
    } catch {
      setToast(t('toast.importPartial'));
    } finally {
      setImportBusy(false);
    }
  }
  async function logout() {
    await supabase.auth.signOut();
    setData((current) => ({ ...current, activeUserId: null }));
  }
  async function buildCardBlob() {
    const canvas = await drawProfileCard({ username: user.username, level: user.level ?? 1, levelTitle: titleForLevel(user.level ?? 1, lang), streak: user.streakCurrent ?? 0, badgesUnlocked: unlockedBadges, badgesTotal: badgeViews.length, tier: topCardTier, lang });
    return new Promise((resolve) => canvas.toBlob(resolve, 'image/png'));
  }
  async function downloadProfileCard() {
    const blob = await buildCardBlob();
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `rapi-kartu-${user.username}.png`;
    link.click();
    URL.revokeObjectURL(url);
  }
  async function shareProfileCard() {
    const blob = await buildCardBlob();
    const file = new File([blob], `rapi-kartu-${user.username}.png`, { type: 'image/png' });
    if (navigator.canShare?.({ files: [file] })) {
      try { await navigator.share({ files: [file], title: t('share.navTitle') }); } catch {}
    } else {
      await downloadProfileCard();
    }
  }
  async function saveGoal(name, amount) {
    const existing = await supabase.from('goals').select('id').eq('user_id', user.id).eq('is_active', true).maybeSingle();
    if (existing.data) await supabase.from('goals').update({ name: name.trim(), amount }).eq('id', existing.data.id);
    else await supabase.from('goals').insert({ user_id: user.id, name: name.trim(), amount });
    setData((current) => ({ ...current, goals: { ...current.goals, [user.id]: { name: name.trim(), amount } } }));
    return true;
  }
  async function saveBudget(category, amount) {
    const { error } = await supabase.from('budgets').upsert({ user_id: user.id, category, monthly_limit: amount });
    if (error) return false;
    setData((current) => ({ ...current, budgets: { ...current.budgets, [user.id]: { ...(current.budgets?.[user.id] ?? {}), [category]: amount } } }));
    return true;
  }
  async function saveCategory({ name, emoji, type }) {
    const cleanName = name.trim();
    const cleanEmoji = Array.from(emoji.trim())[0] ?? '';
    if (!cleanEmoji) return false;
    const { data: row, error } = await supabase.from('categories')
      .upsert({ user_id: user.id, name: cleanName, emoji: cleanEmoji, type }, { onConflict: 'user_id,name' })
      .select()
      .single();
    if (error || !row) return false;
    setData((current) => ({
      ...current,
      categories: { ...current.categories, [user.id]: [...(current.categories[user.id] ?? []).filter((item) => item.name !== cleanName), mapCategory(row)] },
    }));
    return true;
  }
  async function removeCategory(id) {
    const target = (data.categories?.[user.id] ?? []).find((item) => item.id === id);
    if (!target || target.isDefault) return false;
    const { error } = await supabase.from('categories').delete().eq('id', id);
    if (error) return false;
    setData((current) => ({ ...current, categories: { ...current.categories, [user.id]: (current.categories[user.id] ?? []).filter((item) => item.id !== id) } }));
    return true;
  }
  async function addRecurring(payload) {
    const tomorrow = addDays(today, 1);
    const nextRun = occurrenceOnOrAfter({ frequency: payload.frequency, dayOfPeriod: payload.dayOfPeriod }, payload.startDate > tomorrow ? payload.startDate : tomorrow);
    const { data: row, error } = await supabase.from('recurring_transactions')
      .insert({ user_id: user.id, type: payload.type, title: payload.title, amount: payload.amount, category: payload.category, frequency: payload.frequency, day_of_period: payload.dayOfPeriod, next_run_date: nextRun })
      .select()
      .single();
    if (error || !row) return false;
    setData((current) => ({ ...current, recurrings: { ...current.recurrings, [user.id]: [...(current.recurrings?.[user.id] ?? []), mapRecurring(row)] } }));
    return true;
  }
  async function removeRecurring(id) {
    const { error } = await supabase.from('recurring_transactions').delete().eq('id', id);
    if (error) return false;
    setData((current) => ({ ...current, recurrings: { ...current.recurrings, [user.id]: (current.recurrings[user.id] ?? []).filter((item) => item.id !== id) } }));
    return true;
  }
  function setReminderPref(key, value) {
    try { window.localStorage.setItem(key, value); } catch {}
  }
  async function toggleReminders(next) {
    setReminderMsg('');
    try {
      if (!next) {
        setReminderEnabled(false);
        setReminderPref('rapi.reminder.enabled', '0');
        syncReminders({ enabled: false });
        return;
      }
      let state = await reminderPermissionState();
      if (state !== 'granted') state = await requestReminderPermission();
      if (state !== 'granted') return setReminderMsg(t('rem.permDenied'));
      setReminderEnabled(true);
      setReminderPref('rapi.reminder.enabled', '1');
      const ok = await syncReminders({ enabled: true, hour: reminderHour, recurrings, lang });
      if (!ok) return setReminderMsg(t('rem.scheduleFail'));
      await fireTestPing(lang);
      setReminderMsg(t('rem.active'));
    } catch {
      setReminderMsg(t('rem.scheduleFail'));
    }
  }
  async function changeReminderHour(value) {
    const hour = Number(value);
    setReminderHour(hour);
    setReminderPref('rapi.reminder.hour', String(hour));
    if (reminderEnabled) await syncReminders({ enabled: true, hour, recurrings, lang });
  }
  /* Notifikasi terjadwal di-generate ulang saat ganti bahasa agar teksnya ikut bahasa baru */
  useEffect(() => {
    if (reminderEnabled && Capacitor.isNativePlatform()) syncReminders({ enabled: true, hour: reminderHour, recurrings, lang });
    return () => {};
  }, [lang]); // eslint-disable-line react-hooks/exhaustive-deps
  async function claimGoal() {
    if (!goalReached || !window.confirm(t('confirm.claimGoal', { name: goal.name }))) return;
    await supabase.from('achievements').insert({ user_id: user.id, goal_name: goal.name, goal_amount: goal.amount, completed_at: today });
    await supabase.from('goals').update({ is_active: false }).eq('user_id', user.id).eq('is_active', true);
    setData((current) => ({ ...current, goals: { ...current.goals, [user.id]: null }, achievements: { ...current.achievements, [user.id]: [...(current.achievements?.[user.id] ?? []), { ...goal, id: crypto.randomUUID(), completedAt: today }] } }));
  }
  async function deleteAccount() {
    if (!window.confirm(t('confirm.deleteAccount', { name: user.username }))) return;
    await supabase.from('profiles').delete().eq('id', user.id);
    await supabase.auth.signOut();
    setData((current) => {
      const nextTransactions = { ...current.transactions };
      delete nextTransactions[user.id];
      const nextGoals = { ...current.goals }; delete nextGoals[user.id];
      const nextAchievements = { ...current.achievements }; delete nextAchievements[user.id];
      const nextBudgets = { ...current.budgets }; delete nextBudgets[user.id];
      return { users: current.users.filter((item) => item.id !== user.id), transactions: nextTransactions, goals: nextGoals, achievements: nextAchievements, budgets: nextBudgets, activeUserId: null };
    });
  }

  /* Sub-halaman Profil (pola menu Settings): full-replace di dalam tab,
     header kembali + judul + slot aksi kanan. Konten dipindah dari section lama. */
  function ProfileSubPage({ view, onBack }) {
    const meta = {
      kartu: ['🪪', 'prof.menu.kartu'],
      pengaturan: ['⚙️', 'prof.menu.pengaturan'],
      kategori: ['🗂️', 'cat.title'],
      rutin: ['🔁', 'recM.title'],
      data: ['📦', 'data.title'],
      saran: ['💡', 'prof.menu.saran'],
      pengingat: ['🔔', 'rem.title'],
      danger: ['⚠️', 'danger.title'],
    }[view] ?? ['📄', ''];
    const addAction = view === 'kategori' ? () => setCategorySheet(true) : view === 'rutin' ? () => setRecurringSheet(true) : null;
    return <div className="profil-stack profile-sub">
      <header className="sub-header">
        <button type="button" className="sub-back" aria-label={t('prof.back')} onClick={onBack}>←</button>
        <span className="sub-icon" aria-hidden="true">{meta[0]}</span>
        <h2>{t(meta[1])}</h2>
        {addAction && <button type="button" className="clay-button brutal-button sub-action" onClick={addAction}>{view === 'kategori' ? t('cat.add') : t('recM.add')}</button>}
      </header>
      {view === 'kartu' && <article className="share-card clay-card brutal-card brutal-share"><p className="kicker">{t('share.kicker')}</p><div className="share-id"><span className="avatar big" aria-hidden="true">{user.username.slice(0, 1).toUpperCase()}</span><div><strong>{user.username}</strong><small>{t('prof.lvTitle', { lvl: profInfo.level, title: titleForLevel(user.level ?? 1, lang) })}</small></div><b className={`share-tier tier-${topCardTier}`}>{topCardTier}</b></div><ul className="share-stats"><li>🔥<span>{t('pc.statsStreak', { n: user.streakCurrent ?? 0 })}</span></li><li>🏅<span>{t('pc.statsBadge', { a: unlockedBadges, b: badgeViews.length })}</span></li></ul><p className="share-note">{t('share.note')}</p><div className="card-actions"><button className="card-button clay-button brutal-button" onClick={downloadProfileCard}>{t('share.download')}</button>{canShareCard && <button className="card-button ghost-button clay-button brutal-button brutal-ghost" onClick={shareProfileCard}>{t('share.shareBtn')}</button>}</div></article>}
      {view === 'pengaturan' && <article className="brutal-card settings-card">
        <label className="settings-field"><span>{t('settings.currency')}</span>
          <select value={fxCode} onChange={(e) => changeCurrency(e.target.value)} aria-label={t('settings.currencyAria')}>
            {CURRENCIES.map(([code, label]) => <option key={code} value={code}>{label}</option>)}
          </select>
        </label>
        <p className="fx-note">{fxStatus === 'loading' ? t('fx.loading') : fxStatus === 'unavailable' ? t('fx.unavailable') : fxData?.date ? `${t('fx.asOf', { date: fxData.date })}${fxStatus === 'stale' ? t('fx.staleSuffix') : ''}` : t('fx.noteIdr')}</p>
        <div className="settings-field" role="group" aria-label={t('settings.fontSize')}><span>{t('settings.fontSize')}</span>
          <div className="sort-toggle font-scale">
            {[['1', 'font.normal'], ['1.15', 'font.big'], ['1.3', 'font.super']].map(([value, key]) => (
              <button key={value} type="button" className={fontScale === value ? 'active' : ''} aria-pressed={fontScale === value} onClick={() => onChangeFontScale(value)}>{t(key)}</button>
            ))}
          </div>
        </div>
        <div className="settings-field" role="group" aria-label={t('settings.language')}><span>{t('settings.language')}</span>
          <div className="sort-toggle lang-switch">
            {LANGS.map(([value, label]) => (
              <button key={value} type="button" className={lang === value ? 'active' : ''} aria-pressed={lang === value} onClick={() => onChangeLang(value)}>{label}</button>
            ))}
          </div>
        </div>
        <div className="settings-field" role="group" aria-label={t('settings.theme')}><span>{t('settings.theme')}</span>
          <div className="sort-toggle theme-switch">
            {[['system', 'theme.system'], ['light', 'theme.light'], ['dark', 'theme.dark']].map(([value, key]) => (
              <button key={value} type="button" className={theme === value ? 'active' : ''} aria-pressed={theme === value} onClick={() => onChangeTheme(value)}>{t(key)}</button>
            ))}
          </div>
        </div>
      </article>}
      {view === 'kategori' && <article className="category-manage-card brutal-card">
        <CategoryRows label={t('form.income')} items={categories.filter((item) => item.type !== 'expense')} onDelete={removeCategory} />
        <CategoryRows label={t('form.expense')} items={categories.filter((item) => item.type !== 'income')} onDelete={removeCategory} />
      </article>}
      {view === 'rutin' && <article className="brutal-card recurring-manage-card">
        {recurrings.length ? recurrings.map((rule) => <div className="recurring-row" key={rule.id}>
          <span className="category-emoji">{emojiMap[rule.category] ?? '🔁'}</span>
          <div className="recurring-info">
            <strong>{rule.title}</strong>
            <small>{money.format(rule.amount)} · {rule.frequency === 'monthly' ? t('rec.everyMonthDay', { d: rule.dayOfPeriod }) : t('rec.everyWeekday', { day: rule.dayOfPeriod ? t(`wdF.${rule.dayOfPeriod}`) : '' })}</small>
            <small className="muted">{t('rec.next')} {dateFmt().format(new Date(`${rule.nextRunDate}T00:00:00`))}</small>
          </div>
          <button type="button" aria-label={t('tx.deleteAria', { title: rule.title })} onClick={() => removeRecurring(rule.id)}>×</button>
        </div>) : <p className="recurring-empty">{t('recM.empty')}</p>}
      </article>}
      {view === 'data' && <article className="brutal-card data-card">
        <p className="data-note">{t('data.note')}</p>
        <label className="data-label">{t('data.pdfRange')}</label>
        <div className="sort-toggle pdf-range" role="group" aria-label={t('data.pdfRange')}>{[['this', 'pdf.thisMonth'], ['last', 'pdf.lastMonth'], ['custom', 'pdf.custom']].map(([value, key]) => <button key={value} type="button" className={pdfRange === value ? 'active' : ''} onClick={() => setPdfRange(value)}>{t(key)}</button>)}</div>
        {pdfRange === 'custom' && <div className="pdf-custom"><input type="date" value={pdfCustom.start} max={today} onChange={(e) => setPdfCustom((cur) => ({ ...cur, start: e.target.value }))} aria-label={t('data.startAria')} /><span>{t('pdf.to')}</span><input type="date" value={pdfCustom.end} max={today} onChange={(e) => setPdfCustom((cur) => ({ ...cur, end: e.target.value }))} aria-label={t('data.endAria')} /></div>}
        <div className="data-actions">
          <button className="clay-button brutal-button" onClick={handleExportPdf}>{t('data.exportPdf')}</button>
          <button className="clay-button brutal-button brutal-ghost" onClick={handleExportCsv}>{t('data.exportCsv')}</button>
          <button className="clay-button brutal-button brutal-ghost" onClick={() => { setImportPreview(null); setImportSheetOpen(true); }}>{t('data.importCsv')}</button>
        </div>
      </article>}
      {view === 'pengingat' && showReminderCard && <article className="brutal-card reminder-card">
        <div className="reminder-row">
          <div><strong>{t('rem.enable')}</strong><p>{t('rem.desc')}</p></div>
          <button type="button" role="switch" aria-checked={reminderEnabled} aria-label={t('rem.enable')} className={`reminder-toggle ${reminderEnabled ? 'on' : ''}`} onClick={() => toggleReminders(!reminderEnabled)}><i /></button>
        </div>
        {reminderEnabled && <>
          <label className="reminder-hour">{t('rem.hour')}<select value={reminderHour} onChange={(e) => changeReminderHour(e.target.value)}>{[18, 19, 20, 21].map((h) => <option key={h} value={h}>{`${h}:00`}</option>)}</select></label>
          <button type="button" className="clay-button brutal-button brutal-ghost reminder-test" onClick={() => fireTestPing(lang)}>{t('rem.test')}</button>
        </>}
        {reminderMsg && <p className="form-message">{reminderMsg}</p>}
      </article>}
      {view === 'saran' && <article className="brutal-card advice-page">
        <p className="advice-sub">{t('adv.sub')}</p>
        {!advice.items.length ? <div className="advice-empty"><strong>{t('adv.empty.title')}</strong><p>{t('adv.empty.msg')}</p></div> : <>
          {(() => {
            const action = advice.items.filter((item) => item.severity === 'tinggi');
            const reminder = advice.items.filter((item) => item.severity !== 'tinggi');
            return <>
              {action.length > 0 && <section className="advice-group"><p className="kicker">{t('adv.groupAction')}</p>{action.map((item) => <AdviceItem key={item.id} item={item} />)}</section>}
              {reminder.length > 0 && <section className="advice-group"><p className="kicker">{t('adv.groupReminder')}</p>{reminder.map((item) => <AdviceItem key={item.id} item={item} />)}</section>}
            </>;
          })()}
          <p className="advice-disclaimer">{t('adv.disclaimer')}</p>
        </>}
      </article>}
      {view === 'danger' && <section className="danger-zone clay-danger brutal-danger"><div><strong>{t('danger.title')}</strong><p>{t('danger.desc')}</p></div><button className="danger-button clay-button brutal-button brutal-danger-btn" onClick={deleteAccount}>{t('danger.title')}</button></section>}
    </div>;
  }

  return <main className="dashboard-page">
    <div className="dashboard app-frame" id="dashboard">
      {tab === 'beranda' && <>
      <header className="mobile-header"><a className="brand dark brutal-brand" href="#dashboard"><span>r</span> rapi</a></header>
      <section className="dashboard-heading clay-heading brutal-heading">
        <div><p className="kicker">{t('home.kicker')}</p><h1>{t('home.greeting', { name: user.username })} <em>{t('home.greetingEm')}</em></h1><p className="subline">{t('home.subline')}</p></div>
        <button className="clay-button brutal-button" onClick={() => setShowForm(true)}><span>+</span> {t('btn.addTx')}</button>
      </section>
      <section className="summary-grid">
        <BalanceCard balance={balance} hidden={hideBalance} money={money} onToggleHidden={toggleHideBalance} xp={user.xp ?? 0} streak={user.streakCurrent ?? 0} lang={lang} />
        <StatCard label={t('stat.income')} amount={income} icon="↓" variant="income" hidden={hideBalance} money={money} />
        <StatCard label={t('stat.expense')} amount={expense} icon="↑" variant="expense" hidden={hideBalance} money={money} />
      </section>
      {adviceHigh[0] && <button type="button" className="advice-teaser clay-card brutal-card" aria-label={t('adv.seeAll')} onClick={() => { setTab('profil'); setProfileView('saran'); }}>
        <span className="advice-teaser-icon" aria-hidden="true">{adviceHigh[0].icon}</span>
        <span className="advice-teaser-body"><small className="kicker">{t('adv.kicker')}</small><Highlighted text={adviceHigh[0].message} /></span>
        {advice.items.length > 1 && <b className="advice-teaser-count">+{advice.items.length - 1}</b>}
        <span className="row-chevron" aria-hidden="true">›</span>
      </button>}
      <section className="recap-section brutal-section">
        <div className="section-header"><div><p className="kicker">{t('recap.kicker')}</p><h2>{t('recap.title')}</h2></div><div className="sort-toggle recap-toggle" role="group" aria-label={t('recap.toggleAria')}><button type="button" className={recapPeriod === 'week' ? 'active' : ''} onClick={() => setRecapPeriod('week')}>{t('recap.week')}</button><button type="button" className={recapPeriod === 'month' ? 'active' : ''} onClick={() => setRecapPeriod('month')}>{t('recap.month')}</button></div></div>
        {recap.isEmpty ? <article className="brutal-card recap-card recap-empty">{t('recap.empty')}</article> : <article className="brutal-card recap-card">
          {recap.lines.map((line, i) => <p key={i}><Highlighted text={line} /></p>)}
          <div className="recap-stats">
            <div><small>{t('recap.statIn')}</small><b className="in">{money.formatShort(recap.stats.income)}</b></div>
            <div><small>{t('recap.statOut')}</small><b className="out">{money.formatShort(recap.stats.expense)}</b></div>
            <div><small>{t('recap.statDays')}</small><b>{t('recap.daysVal', { n: recap.stats.activeDays })}</b></div>
          </div>
        </article>}
      </section>
      </>}
      {tab === 'target' && <>
      <section className="playful-grid tab-target">
        <article className={`goal-card clay-card clay-goal brutal-card brutal-goal ${goalReached ? 'goal-reached' : ''}`}><div><p className="kicker">{goalReached ? t('goal.kickerDone') : t('goal.kicker')}</p><h2>{goal ? goal.name : t('goal.noGoal')}</h2>{goal ? <><div className="goal-progress"><span style={{ width: `${Math.min(100, Math.max(0, balance / goal.amount * 100))}%` }} /></div><p className="goal-caption"><strong>{money.format(Math.max(0, balance))}</strong> {t('goal.of')} {money.format(goal.amount)}</p></> : <p className="goal-caption">{t('goal.captionEmpty')}</p>}</div>{goalReached ? <button className="claim-goal clay-button brutal-button brutal-success" onClick={claimGoal}>{t('btn.claimBadge')}</button> : <button className="goal-button clay-button brutal-button" onClick={() => setGoalSheet(true)}>{t(goal ? 'btn.editGoal' : 'btn.newGoal')}</button>}</article>
        <article className="badge-card clay-card clay-badge brutal-card brutal-badge"><div className="badge-heading"><div><p className="kicker">{t('badge.kicker')}</p><h2>{t('badge.heading')}</h2></div><span>{unlockedBadges}/{badgeViews.length}</span></div><div className="badges">{badgeViews.map((badge) => <div className={`badge tier-${badge.rarity} ${badge.unlocked ? 'unlocked' : 'locked'}`} key={badge.code}><span>{badge.icon}</span><div><strong>{badge.title}</strong><small>{badge.unlocked ? badge.note : `${Math.min(badge.current, badge.target)}/${badge.target} · ${badge.note}`}</small>{!badge.unlocked && <i className="badge-progress"><em style={{ width: `${badge.progress * 100}%` }} /></i>}</div><b className="badge-tier">{badge.rarity}</b></div>)}</div></article>
      </section>
      </>}
      {tab === 'beranda' && <>
      <section className="insight-section clay-insight brutal-section"><div className="section-header"><div><h2>{t('insight.title')}</h2><p>{t('insight.sub')}</p></div></div><div className="insight-grid"><article className="insight-card clay-card brutal-card"><span>💡</span><div><p className="kicker">{topSpending ? t('insight.topKicker') : t('insight.title')}</p><strong>{topSpending ? `${emojiMap[topSpending.category] ?? '✨'} ${topSpending.category}` : t('insight.none')}</strong>{topSpending && <span className="insight-amount">{money.format(topSpending.amount)}</span>}<p className="insight-caption">{topSpending ? t('insight.captionTop') : t('insight.captionEmpty')}</p></div></article><article className="chart-card clay-card brutal-card"><div className="chart-title"><strong>{t('chart.title')}</strong><span>{t('chart.period')}</span></div>{categorySummary.length ? <div className="chart-bars">{categorySummary.map((item) => <div className="chart-row" key={item.category}><span>{emojiMap[item.category] ?? '✨'}</span><div><div><strong>{item.category}</strong><b>{money.format(item.amount)}</b></div><i><em style={{ width: `${item.amount / chartMax * 100}%` }} /></i></div></div>)}</div> : <p className="chart-empty">{t('chart.empty')}</p>}</article></div></section>
      <section className="budget-section clay-budget brutal-section"><div className="section-header"><div><h2>{t('budget.title')}</h2><p>{t('budget.sub')}</p></div><button className="budget-add clay-button brutal-button" onClick={() => setBudgetSheet({})}>{t('budget.add')}</button></div>{budgetEntries.length ? <div className="budget-grid">{budgetEntries.map(([category, limit]) => { const spent = spendingFor(category); const ratio = spent / limit; const state = ratio >= 1 ? 'over' : ratio >= .8 ? 'near' : 'safe'; return <article className="budget-item clay-card brutal-card" key={category}><div><span>{emojiMap[category] ?? '✨'}</span><strong>{category}</strong><button onClick={() => setBudgetSheet({ category })} aria-label={t('budget.editAria', { category })}>⋯</button></div><div className="budget-bar"><span className={state} style={{ width: `${Math.min(100, ratio * 100)}%` }} /></div><p><b>{money.format(spent)}</b> / {money.format(limit)} <em>{state === 'over' ? t('budget.over') : state === 'near' ? t('budget.near') : t('budget.safe')}</em></p></article>; })}</div> : <div className="budget-empty brutal-empty"><span>🪄</span><div><strong>{t('budget.emptyT')}</strong><p>{t('budget.emptyD')}</p></div><button className="clay-button brutal-button" onClick={() => setBudgetSheet({})}>{t('budget.createBtn')}</button></div>}</section>
      </>}
      {tab === 'transaksi' && <>
      <section className="transactions-section clay-transactions brutal-section">
        <div className="section-header"><div><h2>{t('tx.title')}</h2><p>{t('tx.count', { n: transactions.length })}</p></div><div className="filters brutal-filters">{['all', 'income', 'expense'].map((id) => <button key={id} className={filter === id ? 'active' : ''} onClick={() => setFilter(id)}>{t(`filter.${id}`)}</button>)}</div></div>
        <div className="list-toolbar">
          <div className="category-filters" role="group" aria-label={t('tx.filterAria')}>
            {categoryChips.map((item) => <button key={item.id} type="button" className={categoryFilter === item.name ? 'active' : ''} aria-pressed={categoryFilter === item.name} onClick={() => setCategoryFilter(categoryFilter === item.name ? '' : item.name)}>{item.emoji} {item.name}</button>)}
          </div>
          <div className="sort-toggle" role="group" aria-label={t('tx.sortAria')}>
            <button type="button" className={sortMode === 'newest' ? 'active' : ''} onClick={() => setSortMode('newest')}>{t('sort.newest')}</button>
            <button type="button" className={sortMode === 'amount' ? 'active' : ''} onClick={() => setSortMode('amount')}>{t('sort.biggest')}</button>
          </div>
        </div>
        <div className="transaction-list">
          {visibleTransactions.length ? visibleTransactions.map((item) => <Transaction key={item.id} item={item} emojiMap={emojiMap} money={money} onDelete={removeTransaction} />) : <EmptyState filter={filter} filtered={filter !== 'all' || Boolean(categoryFilter)} onAdd={() => setShowForm(true)} />}
        </div>
      </section>
      </>}
      {tab === 'profil' && (profileView ? <ProfileSubPage view={profileView} onBack={() => setProfileView(null)} /> : <section className="profil-stack">
      <div className="profile-head"><span className="avatar big">{user.username.slice(0, 1).toUpperCase()}</span><div><strong>{user.username}</strong><small>{t('prof.lvTitle', { lvl: profInfo.level, title: titleForLevel(user.level ?? 1, lang) })}</small></div></div>
      <nav className="profile-menu brutal-card" aria-label={t('prof.menu.aria')}>
        {PROFILE_MENU_ROWS.map(([id, icon, labelKey]) => <button key={id} type="button" className="profile-menu-row" onClick={() => setProfileView(id)}><span className="row-icon" aria-hidden="true">{icon}</span><span className="row-label">{t(labelKey)}</span><span className="row-chevron" aria-hidden="true">›</span></button>)}
        {showReminderCard && <button type="button" className="profile-menu-row" onClick={() => setProfileView('pengingat')}><span className="row-icon" aria-hidden="true">🔔</span><span className="row-label">{t('rem.title')}</span><span className="row-chevron" aria-hidden="true">›</span></button>}
        <button type="button" className="profile-menu-row danger" onClick={() => setProfileView('danger')}><span className="row-icon" aria-hidden="true">⚠️</span><span className="row-label">{t('danger.title')}</span><span className="row-chevron" aria-hidden="true">›</span></button>
      </nav>
      <button className="logout-full clay-button brutal-button brutal-ghost" onClick={logout}>{t('auth.logout')}</button>
      </section>)}
    </div>
    {toast && <div className="brutal-toast" role="status">{toast}</div>}
    <BottomNav active={tab} onChange={setTab} onAdd={() => setShowForm(true)} />
    {showForm && <TransactionForm expenseOptions={expenseCategories} incomeOptions={incomeCategories} onClose={() => setShowForm(false)} onSubmit={addTransaction} />}
    {budgetSheet && <BudgetSheet options={expenseCategories} initialCategory={budgetSheet.category ?? ''} currentLimit={budgetSheet.category ? budgets[budgetSheet.category] : ''} onClose={() => setBudgetSheet(null)} onSubmit={saveBudget} />}
    {goalSheet && <GoalSheet goal={goal} onClose={() => setGoalSheet(false)} onSubmit={saveGoal} />}
    {categorySheet && <CategorySheet existingNames={categories.map((item) => item.name)} onClose={() => setCategorySheet(false)} onSubmit={saveCategory} />}
    {recurringSheet && <RecurringSheet categories={categories} onClose={() => setRecurringSheet(false)} onSubmit={addRecurring} />}
    {importSheetOpen && <ImportSheet preview={importPreview} busy={importBusy} money={money} onClose={() => { setImportSheetOpen(false); setImportPreview(null); }} onFile={handleImportFile} onReset={() => setImportPreview(null)} onConfirm={confirmImport} />}
    {levelUp && <LevelUpModal {...levelUp} title={titleForLevel(levelUp.level, lang)} onClose={() => setLevelUp(null)} />}
  </main>;
}

function BalanceCard({ balance, hidden = false, onToggleHidden, xp, streak = 0, money, lang = 'id' }) {
  const info = levelProgress(xp, lang);
  return <article className="balance-card clay-card brutal-card"><div><div className="balance-label-row"><p>{t('balance.label')}</p><button type="button" className="eye-toggle" aria-pressed={hidden} aria-label={hidden ? t('balance.ariaShow') : t('balance.ariaHide')} onClick={onToggleHidden}>{hidden ? '🙈' : '👁️'}</button></div><strong>{hidden ? MASKED_AMOUNT : money.format(balance)}</strong><small>{balance >= 0 ? t('balance.ok') : t('balance.neg')}</small><div className="level-strip"><div className="level-chip"><b>Lv {info.level}</b><span>{info.title}</span></div><div className="level-bar" role="progressbar" aria-valuenow={info.percent} aria-valuemin={0} aria-valuemax={100} aria-label={t('xp.progressAria', { lvl: info.level + 1 })}><span style={{ width: `${info.percent}%` }} /></div><small>{t('xp.toNext', { a: info.xpIntoLevel, b: info.xpForNextLevel, lvl: info.level + 1 })}</small><div className={`streak-chip ${streak > 0 ? 'active' : 'idle'}`}>{streak > 0 ? t('streak.active', { n: streak }) : t('streak.start')}</div></div></div><div className="balance-mark">Rp</div></article>;
}
function StatCard({ label, amount, icon, variant, hidden = false, money }) { return <article className={`stat-card clay-card brutal-card ${variant}`}><span className={`stat-icon ${variant}`}>{icon}</span><div><p>{label}</p><strong>{hidden ? MASKED_AMOUNT : money.format(amount)}</strong><small>{variant === 'income' ? t('stat.incomeSub') : t('stat.expenseSub')}</small></div></article>; }

function Transaction({ item, emojiMap = {}, onDelete , money }) {
  const income = item.type === 'income';
  return <article className="transaction clay-card brutal-card brutal-row"><span className={`transaction-icon ${income ? 'income' : 'expense'}`}>{emojiMap[item.category] || '✨'}</span><div className="transaction-info"><strong>{item.title}</strong><span>{item.category} <i>•</i> {dateFmt().format(new Date(`${item.date}T00:00:00`))}</span></div><strong className={income ? 'amount income-text' : 'amount expense-text'}>{income ? '+' : '−'} {money.format(item.amount)}</strong><button className="delete-transaction" aria-label={t('tx.deleteAria', { title: item.title })} onClick={() => onDelete(item.id)}>×</button></article>;
}

function EmptyState({ filter, filtered = false, onAdd }) { return <div className="empty brutal-empty-state"><span>⌁</span><h3>{filtered ? t('empty.filtered') : filter === 'all' ? t('empty.all') : t('empty.type')}</h3><p>{filtered ? t('empty.filteredHint') : t('empty.hint')}</p>{filter === 'all' && !filtered && <button className="empty-button clay-button brutal-button" onClick={onAdd}>{t('btn.addTx')}</button>}</div>; }

function TransactionForm({ expenseOptions = [], incomeOptions = [], onClose, onSubmit }) {
  const [type, setType] = useState('expense');
  const [title, setTitle] = useState('');
  const [amount, setAmount] = useState('');
  const [category, setCategory] = useState('');
  const [date, setDate] = useState(today);
  const [message, setMessage] = useState('');
  const categories = type === 'income' ? incomeOptions : expenseOptions;
  async function submit(event) {
    event.preventDefault();
    const numericAmount = Number(amount);
    if (!title.trim() || !category || !date || !Number.isFinite(numericAmount) || numericAmount <= 0) return setMessage(t('err.completeTx'));
    const saved = await onSubmit({ title: title.trim(), amount: numericAmount, category, date, type });
    if (!saved) setMessage(t('err.saveTx'));
  }
  return <div className="modal-backdrop clay-modal brutal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal clay-card brutal-sheet" role="dialog" aria-modal="true" aria-labelledby="form-title" onMouseDown={(event) => event.stopPropagation()}><button className="close-modal" onClick={onClose} aria-label={t('common.close')}>×</button><p className="kicker">{t('form.tx.kicker')}</p><h2 id="form-title">{t('form.tx.title')}</h2><form onSubmit={submit}><div className="type-switch"><button type="button" className={type === 'expense' ? 'selected expense' : ''} onClick={() => { setType('expense'); setCategory(''); }}>{t('form.expense')}</button><button type="button" className={type === 'income' ? 'selected income' : ''} onClick={() => { setType('income'); setCategory(''); }}>{t('form.income')}</button></div><label>{t('label.name')}<input autoFocus value={title} onChange={(e) => setTitle(e.target.value)} placeholder={type === 'income' ? t('form.tx.phIncome') : t('form.tx.phExpense')} /></label><label>{t('label.amount')}<input inputMode="numeric" value={amount} onChange={(e) => setAmount(e.target.value.replace(/[^0-9]/g, ''))} placeholder={t('form.tx.phAmount')} /></label><div className="form-pair"><label>{t('label.category')}<select value={category} onChange={(e) => setCategory(e.target.value)}><option value="">{t('opt.pickCategory')}</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label>{t('label.date')}<input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label></div>{message && <p className="form-message">{message}</p>}<div className="form-actions"><button className="ghost-button clay-button brutal-button brutal-ghost" type="button" onClick={onClose}>{t('common.cancel')}</button><button className="primary-button clay-button brutal-button" type="submit">{t('btn.saveTx')} <span>→</span></button></div></form></section></div>;
}

function BudgetSheet({ options = [], initialCategory = '', currentLimit = '', onClose, onSubmit }) {
  const [category, setCategory] = useState(initialCategory);
  const [amount, setAmount] = useState(currentLimit ? String(currentLimit) : '');
  const [message, setMessage] = useState('');
  async function submit(event) {
    event.preventDefault();
    const numericAmount = Number(amount);
    if (!category || !options.includes(category)) return setMessage(t('err.pickCategory'));
    if (!Number.isFinite(numericAmount) || numericAmount <= 0) return setMessage(t('err.badLimit'));
    if (!(await onSubmit(category, numericAmount))) return setMessage(t('err.saveBudget'));
    onClose();
  }
  return <div className="modal-backdrop clay-modal brutal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal clay-card brutal-sheet" role="dialog" aria-modal="true" aria-labelledby="budget-title" onMouseDown={(event) => event.stopPropagation()}><button className="close-modal" onClick={onClose} aria-label={t('common.close')}>×</button><p className="kicker">{t('form.budget.kicker')}</p><h2 id="budget-title">{t(initialCategory ? 'form.budget.edit' : 'form.budget.new')}</h2><form onSubmit={submit}><label>{t('label.category')}<select value={category} onChange={(e) => setCategory(e.target.value)}><option value="">{t('opt.pickCategory')}</option>{options.map((item) => <option key={item}>{item}</option>)}</select></label><label>{t('form.budget.limitLabel')}<input inputMode="numeric" value={amount} onChange={(e) => setAmount(e.target.value.replace(/[^0-9]/g, ''))} placeholder={t('form.budget.ph')} /></label>{message && <p className="form-message">{message}</p>}<div className="form-actions"><button className="ghost-button clay-button brutal-button brutal-ghost" type="button" onClick={onClose}>{t('common.cancel')}</button><button className="primary-button clay-button brutal-button" type="submit">{t('btn.saveBudget')} <span>→</span></button></div></form></section></div>;
}

function GoalSheet({ goal, onClose, onSubmit }) {
  const [name, setName] = useState(goal?.name ?? '');
  const [amount, setAmount] = useState(goal?.amount ? String(goal.amount) : '');
  const [message, setMessage] = useState('');
  async function submit(event) {
    event.preventDefault();
    const numericAmount = Number(amount);
    if (!name.trim()) return setMessage(t('err.goalName'));
    if (!Number.isFinite(numericAmount) || numericAmount <= 0) return setMessage(t('err.badGoalAmount'));
    if (!(await onSubmit(name.trim(), numericAmount))) return setMessage(t('err.saveGoal'));
    onClose();
  }
  return <div className="modal-backdrop clay-modal brutal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal clay-card brutal-sheet" role="dialog" aria-modal="true" aria-labelledby="goal-title" onMouseDown={(event) => event.stopPropagation()}><button className="close-modal" onClick={onClose} aria-label={t('common.close')}>×</button><p className="kicker">{t('goal.kicker')}</p><h2 id="goal-title">{t(goal ? 'form.goal.edit' : 'form.goal.new')}</h2><form onSubmit={submit}><label>{t('form.goal.name')}<input value={name} onChange={(e) => setName(e.target.value)} placeholder={t('form.goal.ph')} /></label><label>{t('form.goal.amount')}<input inputMode="numeric" value={amount} onChange={(e) => setAmount(e.target.value.replace(/[^0-9]/g, ''))} placeholder={t('form.goal.phAmount')} /></label>{message && <p className="form-message">{message}</p>}<div className="form-actions"><button className="ghost-button clay-button brutal-button brutal-ghost" type="button" onClick={onClose}>{t('common.cancel')}</button><button className="primary-button clay-button brutal-button" type="submit">{t('btn.saveGoal')} <span>→</span></button></div></form></section></div>;
}

function CategoryRows({ label, items, onDelete }) {
  return <div className="category-group">
    <small>{label}</small>
    {items.map((item) => <div className="category-row" key={item.id}>
      <span className="category-emoji">{item.emoji}</span>
      <strong>{item.name}</strong>
      {item.isDefault && <em>{t('cat.defaultChip')}</em>}
      {!item.isDefault && <button type="button" aria-label={t('cat.deleteAria', { name: item.name })} onClick={() => onDelete(item.id)}>×</button>}
    </div>)}
  </div>;
}

function CategorySheet({ existingNames = [], onClose, onSubmit }) {
  const [type, setType] = useState('expense');
  const [emoji, setEmoji] = useState('');
  const [name, setName] = useState('');
  const [message, setMessage] = useState('');
  async function submit(event) {
    event.preventDefault();
    const cleanName = name.trim();
    const cleanEmoji = Array.from(emoji.trim())[0] ?? '';
    if (!cleanName) return setMessage(t('err.catName'));
    if (existingNames.some((item) => item.toLowerCase() === cleanName.toLowerCase())) return setMessage(t('err.catDup'));
    if (!cleanEmoji) return setMessage(t('err.pickEmoji'));
    if (!(await onSubmit({ name: cleanName, emoji: cleanEmoji, type }))) return setMessage(t('err.saveCat'));
    onClose();
  }
  return <div className="modal-backdrop clay-modal brutal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal clay-card brutal-sheet" role="dialog" aria-modal="true" aria-labelledby="category-title" onMouseDown={(event) => event.stopPropagation()}><button className="close-modal" onClick={onClose} aria-label={t('common.close')}>×</button><p className="kicker">{t('form.cat.kicker')}</p><h2 id="category-title">{t('form.cat.title')}</h2><form onSubmit={submit}><div className="type-switch"><button type="button" className={type === 'expense' ? 'selected expense' : ''} onClick={() => setType('expense')}>{t('form.expense')}</button><button type="button" className={type === 'income' ? 'selected income' : ''} onClick={() => setType('income')}>{t('form.income')}</button><button type="button" className={type === 'both' ? 'selected both' : ''} onClick={() => setType('both')}>{t('form.both')}</button></div><label>{t('form.cat.name')}<input value={name} onChange={(e) => setName(e.target.value)} maxLength={24} placeholder={t('form.cat.ph')} /></label><label>{t('form.cat.emoji')}<div className="emoji-field"><span>{Array.from(emoji.trim())[0] || '❓'}</span><input value={emoji} onChange={(e) => setEmoji(e.target.value)} maxLength={8} placeholder="📦" /></div></label>{message && <p className="form-message">{message}</p>}<div className="form-actions"><button className="ghost-button clay-button brutal-button brutal-ghost" type="button" onClick={onClose}>{t('common.cancel')}</button><button className="primary-button clay-button brutal-button" type="submit">{t('btn.saveCat')} <span>→</span></button></div></form></section></div>;
}

function RecurringSheet({ categories = [], onClose, onSubmit }) {
  const [type, setType] = useState('expense');
  const [title, setTitle] = useState('');
  const [amount, setAmount] = useState('');
  const [frequency, setFrequency] = useState('monthly');
  const [dayOfPeriod, setDayOfPeriod] = useState('');
  const [category, setCategory] = useState('');
  const [startDate, setStartDate] = useState(today);
  const [message, setMessage] = useState('');
  const options = categories.filter((item) => item.type === type || item.type === 'both');
  async function submit(event) {
    event.preventDefault();
    const numericAmount = Number(amount);
    if (!title.trim()) return setMessage(t('err.recName'));
    if (!Number.isFinite(numericAmount) || numericAmount <= 0) return setMessage(t('err.badAmount'));
    if (!category) return setMessage(t('err.pickCategory'));
    if (!dayOfPeriod) return setMessage(frequency === 'monthly' ? t('err.pickBillDate') : t('err.pickBillDay'));
    if (!startDate) return setMessage(t('err.pickStart'));
    if (!(await onSubmit({ type, title: title.trim(), amount: numericAmount, category, frequency, dayOfPeriod: Number(dayOfPeriod), startDate }))) return setMessage(t('err.saveRec'));
    onClose();
  }
  return <div className="modal-backdrop clay-modal brutal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal clay-card brutal-sheet" role="dialog" aria-modal="true" aria-labelledby="recurring-title" onMouseDown={(event) => event.stopPropagation()}><button className="close-modal" onClick={onClose} aria-label={t('common.close')}>×</button><p className="kicker">{t('form.rec.kicker')}</p><h2 id="recurring-title">{t('form.rec.title')}</h2><form onSubmit={submit}><div className="type-switch"><button type="button" className={type === 'expense' ? 'selected expense' : ''} onClick={() => { setType('expense'); setCategory(''); }}>{t('form.expense')}</button><button type="button" className={type === 'income' ? 'selected income' : ''} onClick={() => { setType('income'); setCategory(''); }}>{t('form.income')}</button></div><label>{t('form.rec.name')}<input value={title} onChange={(e) => setTitle(e.target.value)} maxLength={30} placeholder={t('form.rec.ph')} /></label><label>{t('label.amount')}<input inputMode="numeric" value={amount} onChange={(e) => setAmount(e.target.value.replace(/[^0-9]/g, ''))} placeholder={t('form.rec.phAmount')} /></label><div className="form-pair"><label>{t('form.rec.freq')}<select value={frequency} onChange={(e) => { setFrequency(e.target.value); setDayOfPeriod(''); }}><option value="monthly">{t('rec.monthly')}</option><option value="weekly">{t('rec.weekly')}</option></select></label><label>{t('label.category')}<select value={category} onChange={(e) => setCategory(e.target.value)}><option value="">{t('opt.pickCategory')}</option>{options.map((item) => <option key={item.name}>{item.name}</option>)}</select></label></div>{frequency === 'monthly' ? <label>{t('form.rec.billDate')}<select value={dayOfPeriod} onChange={(e) => setDayOfPeriod(e.target.value)}><option value="">{t('rec.pickDay')}</option>{Array.from({ length: 28 }, (_, i) => i + 1).map((d) => <option key={d} value={d}>{t('rec.dayN', { d })}</option>)}</select></label> : <label>{t('form.rec.billDay')}<div className="weekday-chips">{[1, 2, 3, 4, 5, 6, 7].map((d) => <button type="button" key={d} className={String(dayOfPeriod) === String(d) ? 'selected' : ''} onClick={() => setDayOfPeriod(String(d))}>{t(`wd.${d}`)}</button>)}</div></label>}<label>{t('form.rec.startDate')}<input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} /></label>{message && <p className="form-message">{message}</p>}<div className="form-actions"><button className="ghost-button clay-button brutal-button brutal-ghost" type="button" onClick={onClose}>{t('common.cancel')}</button><button className="primary-button clay-button brutal-button" type="submit">{t('btn.saveRec')} <span>→</span></button></div></form></section></div>;
}

function Highlighted({ text }) {
  const parts = String(text).split(/\*\*(.+?)\*\*/g);
  return <>{parts.map((part, i) => (i % 2 ? <em key={i}>{part}</em> : part))}</>;
}

function AdviceItem({ item }) {
  return <div className={`advice-item sev-${item.severity}`}>
    <span className="advice-item-icon" aria-hidden="true">{item.icon}</span>
    <div className="advice-item-body">
      <div className="advice-item-head"><strong>{item.title}</strong><span className="advice-sev">{t(`adv.sev.${item.severity}`)}</span></div>
      <p><Highlighted text={item.message} /></p>
      <small className="muted">{item.reason}</small>
    </div>
  </div>;
}

function ImportSheet({ preview, busy, onClose, onFile, onReset, onConfirm, money }) {
  const result = preview?.result;
  const validCount = result?.valid.length ?? 0;
  const sample = result?.valid.slice(0, 5) ?? [];
  return <div className="modal-backdrop clay-modal brutal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal clay-card brutal-sheet" role="dialog" aria-modal="true" aria-labelledby="import-title" onMouseDown={(event) => event.stopPropagation()}><button className="close-modal" onClick={onClose} aria-label={t('common.close')}>×</button><p className="kicker">{t('import.kicker')}</p><h2 id="import-title">{t('import.title')}</h2>
    {!preview ? <>
      <p className="import-hint"><Highlighted text={t('import.hint')} /></p>
      <label className="import-drop">
        <input type="file" accept=".csv,text/csv" onChange={onFile} />
        <span className="import-drop-inner"><b>{t('import.pick')}</b><small>{t('import.max')}</small></span>
      </label>
    </> : !result.headerOk ? <>
      <div className="import-errors"><p>❌ {result.invalid[0]?.reason}</p></div>
      <button className="clay-button brutal-button brutal-ghost import-confirm" onClick={onReset}>{t('import.retry')}</button>
    </> : <>
      <p className="import-filename">{preview.fileName}</p>
      <div className="import-summary">
        {validCount > 0 && <span className="ok">✅ {t('import.ready', { n: validCount })}</span>}
        {result.duplicateCount > 0 && <span className="dup">🔁 {t('import.dups', { n: result.duplicateCount })}</span>}
        {result.invalid.length > 0 && <span className="bad">⚠️ {t('import.badRows', { n: result.invalid.length })}</span>}
        {!validCount && !result.invalid.length && <span className="dup">{t('import.empty')}</span>}
      </div>
      {result.invalid.length > 0 && <ul className="import-errors">{result.invalid.slice(0, 5).map((item) => <li key={item.row}><b>{t('import.row', { n: item.row })}</b> — {item.reason}</li>)}{result.invalid.length > 5 && <li className="muted">{t('import.moreErrors', { n: result.invalid.length - 5 })}</li>}</ul>}
      {sample.length > 0 && <table className="import-sample"><thead><tr><th>{t('label.date')}</th><th>{t('imp.thTitle')}</th><th>{t('label.amount')}</th></tr></thead><tbody>{sample.map((row, i) => <tr key={i}><td>{row.date}</td><td>{row.title}</td><td className={row.type === 'income' ? 'in' : 'out'}>{money.format(row.amount)}</td></tr>)}</tbody></table>}
      <button className="clay-button brutal-button primary-button import-confirm" disabled={busy || !validCount} onClick={onConfirm}>{busy ? t('import.busy') : t('import.confirm', { n: validCount })}</button>
    </>}
  </section></div>;
}
