'use client';

import { useEffect, useMemo, useState } from 'react';
import { Capacitor } from '@capacitor/core';
import { App as CapacitorApp } from '@capacitor/app';
import supabase from '../lib/supabase';
import { hitungXpEarned, levelFromXp, levelProgress, titleForLevel } from '../lib/xp';
import { nextStreak } from '../lib/streak';
import { badgeStats, evaluateBadges, FALLBACK_BADGE_DEFS } from '../lib/badges';
import { drawProfileCard } from '../lib/profileCard';
import { addDays, generateDue, occurrenceOnOrAfter } from '../lib/recurring';
import { fireTestPing, reminderPermissionState, requestReminderPermission, syncReminders } from '../lib/reminders';
import LevelUpModal from './LevelUpModal';

const rupiah = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 });
const dateFormatter = new Intl.DateTimeFormat('id-ID', { day: 'numeric', month: 'short', year: 'numeric' });
const today = new Date().toISOString().slice(0, 10);

const initialData = { users: [], transactions: {}, goals: {}, achievements: {}, budgets: {}, badges: {}, badgeDefs: [], categories: {}, recurrings: {}, activeUserId: null };
/* Seed kategori default (is_default) — dipakai saat user belum punya baris di tabel categories.
   Lainnya bertipe 'both' supaya muncul di dropdown pemasukan & pengeluaran. */
const DEFAULT_CATEGORIES = [
  ['Makan & Minum', '🍜', 'expense'],
  ['Transportasi', '🛵', 'expense'],
  ['Belanja', '🛍️', 'expense'],
  ['Tagihan', '🧾', 'expense'],
  ['Hiburan', '🎮', 'expense'],
  ['Gaji', '💼', 'income'],
  ['Bonus', '🎉', 'income'],
  ['Usaha', '🏪', 'income'],
  ['Investasi', '📈', 'income'],
  ['Lainnya', '✨', 'both'],
];
const NAV_TABS = [['beranda', '🏠', 'Beranda'], ['transaksi', '💸', 'Transaksi'], ['target', '🎯', 'Target'], ['profil', '👤', 'Profil']];
const WEEKDAY_LABELS = ['', 'Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu'];
const MASKED_AMOUNT = 'Rp ••••••';

function mapTransaction(row) {
  return { id: row.id, type: row.type, title: row.title, amount: Number(row.amount), category: row.category, date: row.date, xp_earned: row.xp_earned ?? 0 };
}

function mapCategory(row) {
  return { id: row.id, name: row.name, emoji: row.emoji, type: row.type, isDefault: Boolean(row.is_default) };
}

function mapRecurring(row) {
  return { id: row.id, type: row.type, title: row.title, amount: Number(row.amount), category: row.category, frequency: row.frequency, dayOfPeriod: row.day_of_period, nextRunDate: row.next_run_date };
}

async function loadData(userId) {
  const [trx, goal, ach, bud, defs, owned, cats, recs] = await Promise.all([
    supabase.from('transactions').select('*').eq('user_id', userId),
    supabase.from('goals').select('*').eq('user_id', userId).eq('is_active', true).maybeSingle(),
    supabase.from('achievements').select('*').eq('user_id', userId),
    supabase.from('budgets').select('*').eq('user_id', userId),
    supabase.from('badge_defs').select('*'),
    supabase.from('user_badges').select('badge_code').eq('user_id', userId),
    supabase.from('categories').select('*').eq('user_id', userId).order('created_at'),
    supabase.from('recurring_transactions').select('*').eq('user_id', userId).eq('is_active', true).order('next_run_date'),
  ]);
  return {
    transactions: (trx.data ?? []).map(mapTransaction),
    goal: goal.data ? { name: goal.data.name, amount: Number(goal.data.amount) } : null,
    achievements: (ach.data ?? []).map((row) => ({ id: row.id, name: row.goal_name, amount: Number(row.goal_amount), completedAt: row.completed_at })),
    budgets: Object.fromEntries((bud.data ?? []).map((row) => [row.category, Number(row.monthly_limit)])),
    badgeDefs: (defs.data ?? []).length ? defs.data : FALLBACK_BADGE_DEFS,
    badges: (owned.data ?? []).map((row) => row.badge_code),
    categories: (cats.data ?? []).map(mapCategory),
    recurrings: (recs.data ?? []).map(mapRecurring),
  };
}

export default function Home() {
  const [data, setData] = useState(initialData);
  const [ready, setReady] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(0);

  async function enterApp(authUser, fallbackName) {
    let profile = (await supabase.from('profiles').select('*').eq('id', authUser.id).maybeSingle()).data;
    if (!profile) {
      const username = fallbackName || authUser.email.replace(/@rapi\.local$/, '');
      profile = (await supabase.from('profiles').insert({ id: authUser.id, username }).select().single()).data
        ?? { id: authUser.id, username, xp: 0, level: 1 };
    }
    const snapshot = await loadData(authUser.id);
    let categories = snapshot.categories;
    if (!categories.length) {
      const { data: seeded, error } = await supabase.from('categories')
        .upsert(
          DEFAULT_CATEGORIES.map(([name, emoji, type]) => ({ user_id: authUser.id, name, emoji, type, is_default: true })),
          { onConflict: 'user_id,name' },
        )
        .select();
      if (!error && seeded?.length) categories = seeded.map(mapCategory);
    }
    let recurrings = snapshot.recurrings;
    let autoCount = 0;
    try {
      const { rows, updates, generated } = generateDue(recurrings, today);
      if (rows.length) {
        const { error } = await supabase.from('transactions').insert(rows.map((row) => ({ ...row, user_id: authUser.id, xp_earned: 0 })));
        if (!error) {
          autoCount = generated;
          await Promise.all(updates.map((item) => supabase.from('recurring_transactions').update({ next_run_date: item.nextRunDate }).eq('id', item.id)));
          recurrings = recurrings.map((rule) => {
            const update = updates.find((item) => item.id === rule.id);
            return update ? { ...rule, nextRunDate: update.nextRunDate } : rule;
          });
        }
      }
    } catch {}
    setAutoGenerated(autoCount);
    if (typeof window !== 'undefined' && window.localStorage.getItem('rapi.reminder.enabled') === '1') {
      const reminderHour = Number(window.localStorage.getItem('rapi.reminder.hour')) || 20;
      await syncReminders({ enabled: true, hour: reminderHour, recurrings });
    }
    const account = { id: authUser.id, username: profile.username, xp: profile.xp ?? 0, level: profile.level ?? 1, streakCurrent: profile.streak_current ?? 0, streakLongest: profile.streak_longest ?? 0 };
    setData((current) => ({
      ...current,
      users: current.users.some((user) => user.id === authUser.id)
        ? current.users.map((user) => (user.id === authUser.id ? account : user))
        : [...current.users, account],
      transactions: { ...current.transactions, [authUser.id]: snapshot.transactions },
      goals: { ...current.goals, [authUser.id]: snapshot.goal },
      achievements: { ...current.achievements, [authUser.id]: snapshot.achievements },
      budgets: { ...current.budgets, [authUser.id]: snapshot.budgets },
      badges: { ...current.badges, [authUser.id]: snapshot.badges },
      badgeDefs: snapshot.badgeDefs,
      categories: { ...current.categories, [authUser.id]: categories },
      recurrings: { ...current.recurrings, [authUser.id]: recurrings },
      activeUserId: authUser.id,
    }));
    setReady(true);
  }

  useEffect(() => {
    supabase.auth.getSession().then(async ({ data: { session } }) => {
      if (session?.user) await enterApp(session.user);
      else setReady(true);
    });
  }, []);

  const activeUser = data.users.find((user) => user.id === data.activeUserId) ?? null;
  if (!ready) return <div className="loading"><span className="loading-dot" />Memuat catatan Anda…</div>;

  return activeUser
    ? <Dashboard user={activeUser} data={data} setData={setData} autoGenerated={autoGenerated} />
    : <Auth onEnter={enterApp} />;
}

function BottomNav({ active, onChange, onAdd }) {
  const item = ([id, icon, label]) => <button key={id} type="button" className={`bottom-nav-item ${active === id ? 'active' : ''}`} aria-current={active === id ? 'page' : undefined} onClick={() => onChange(id)}><span>{icon}</span><small>{label}</small></button>;
  return <nav className="bottom-nav brutal-nav" aria-label="Navigasi utama">
    {item(NAV_TABS[0])}
    {item(NAV_TABS[1])}
    <div className="nav-fab-slot">
      <button type="button" className="nav-fab" aria-label="Catat transaksi baru" onClick={onAdd}>+</button>
    </div>
    {item(NAV_TABS[2])}
    {item(NAV_TABS[3])}
  </nav>;
}

function Auth({ onEnter }) {
  const [mode, setMode] = useState('login');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [message, setMessage] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  async function submit(event) {
    event.preventDefault();
    if (isSubmitting) return;
    const cleanName = username.trim();
    if (cleanName.length < 3) return setMessage('Nama pengguna minimal 3 karakter.');
    if (password.length < 6) return setMessage('Kata sandi minimal 6 karakter.');

    const email = `${cleanName.toLowerCase()}@rapi.local`;
    setIsSubmitting(true);
    try {
      if (mode === 'register') {
        const { data: authData, error } = await supabase.auth.signUp({ email, password });
        if (error) {
          if (/already registered|already exists/i.test(error.message)) setMessage('Nama pengguna sudah digunakan. Coba nama lain.');
          else if (error.code === 'weak_password' || /weak password|at least \d+ characters/i.test(error.message)) setMessage('Kata sandi terlalu lemah, gunakan minimal 6 karakter.');
          else if (error.code === 'over_request_rate_limit' || /rate limit/i.test(error.message)) setMessage('Terlalu banyak percobaan. Tunggu sebentar lalu coba lagi ya.');
          else setMessage(`Pendaftaran gagal: ${error.message}`);
          return;
        }
        if (!authData.session) return setMessage('Akun berhasil dibuat. Silakan masuk.');
        onEnter(authData.user, cleanName);
        return;
      }

      const { data: authData, error } = await supabase.auth.signInWithPassword({ email, password });
      if (error || !authData.user) return setMessage('Nama pengguna atau kata sandi belum tepat.');
      onEnter(authData.user);
    } finally {
      setIsSubmitting(false);
    }
  }

  function changeMode(next) {
    setMode(next); setMessage(''); setUsername(''); setPassword('');
  }

  return <main className="auth-page clay-auth brutal-auth">
    <section className="auth-intro">
      <a className="brand dark brutal-brand" href="#top"><span>r</span> rapi</a>
      <div className="intro-copy">
        <p className="kicker">Rekap Arus Pengeluaran dan Income</p>
        <h1>Uang lebih tenang,<br /><em>hidup lebih lega.</em></h1>
        <p>Catat setiap pemasukan dan pengeluaran dengan cara yang sederhana, aman, dan sepenuhnya milik Anda.</p>
      </div>
      <div className="feature-note"><span>✦</span><div><strong>Pribadi di perangkat Anda</strong><small>Data tersimpan di browser ini saja.</small></div></div>
    </section>
    <section className="auth-panel" id="top">
      <div className="form-wrap clay-card brutal-card">
        <p className="welcome">{mode === 'login' ? 'Selamat datang kembali' : 'Mulai catatan baru'}</p>
        <h2>{mode === 'login' ? 'Masuk ke akun Anda' : 'Buat akun gratis'}</h2>
        <p className="form-description">{mode === 'login' ? 'Masukkan akun Anda untuk melanjutkan.' : 'Tidak perlu email, hanya butuh nama pengguna dan kata sandi.'}</p>
        <form onSubmit={submit}>
          <label>Nama pengguna<input value={username} onChange={(e) => setUsername(e.target.value)} placeholder="Username" autoComplete="username" /></label>
          <label>Kata sandi<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Minimal 6 karakter" autoComplete={mode === 'login' ? 'current-password' : 'new-password'} /></label>
          {message && <p className="form-message" role="alert">{message}</p>}
          <button className="primary-button clay-button brutal-button" type="submit" disabled={isSubmitting}>{isSubmitting ? 'Memproses...' : mode === 'login' ? 'Masuk' : 'Buat akun'}{!isSubmitting && <span>→</span>}</button>
        </form>
        <p className="switch-form">{mode === 'login' ? 'Belum punya akun?' : 'Sudah punya akun?'} <button className="brutal-switch" onClick={() => changeMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Buat akun' : 'Masuk'}</button></p>
        <p className="privacy">Untuk aplikasi demo, akun dan data disimpan lokal di perangkat ini.</p>
      </div>
    </section>
  </main>;
}

function Dashboard({ user, data, setData, autoGenerated = 0 }) {
  const [tab, setTab] = useState('beranda');
  const [showForm, setShowForm] = useState(false);
  const [budgetSheet, setBudgetSheet] = useState(null);
  const [goalSheet, setGoalSheet] = useState(false);
  const [categorySheet, setCategorySheet] = useState(false);
  const [recurringSheet, setRecurringSheet] = useState(false);
  const [filter, setFilter] = useState('all');
  const [levelUp, setLevelUp] = useState(null);
  const [toast, setToast] = useState('');
  const showReminderCard = Capacitor.isNativePlatform();
  const [reminderEnabled, setReminderEnabled] = useState(() => typeof window !== 'undefined' && window.localStorage.getItem('rapi.reminder.enabled') === '1');
  const [reminderHour, setReminderHour] = useState(() => Number(typeof window !== 'undefined' && window.localStorage.getItem('rapi.reminder.hour')) || 20);
  const [reminderMsg, setReminderMsg] = useState('');
  const [hideBalance, setHideBalance] = useState(() => typeof window !== 'undefined' && window.localStorage.getItem('rapi.balance.hidden') === '1');
  const [categoryFilter, setCategoryFilter] = useState('');
  const [sortMode, setSortMode] = useState('newest');
  function toggleHideBalance() {
    setHideBalance((current) => {
      const next = !current;
      try { window.localStorage.setItem('rapi.balance.hidden', next ? '1' : '0'); } catch {}
      return next;
    });
  }
  useEffect(() => {
    if (!autoGenerated) return;
    setToast(autoGenerated === 1 ? '1 transaksi rutin otomatis tercatat ✨' : `${autoGenerated} transaksi rutin otomatis tercatat ✨`);
    const timer = setTimeout(() => setToast(''), 4000);
    return () => clearTimeout(timer);
  }, [autoGenerated]);
  useEffect(() => {
    if (!Capacitor.isNativePlatform()) return;
    const subscription = CapacitorApp.addListener('backButton', () => {
      if (levelUp) setLevelUp(null);
      else if (showForm) setShowForm(false);
      else if (budgetSheet) setBudgetSheet(null);
      else if (goalSheet) setGoalSheet(false);
      else if (categorySheet) setCategorySheet(false);
      else if (recurringSheet) setRecurringSheet(false);
      else if (tab !== 'beranda') setTab('beranda');
      else CapacitorApp.exitApp();
    });
    return () => subscription.remove();
  }, [tab, showForm, budgetSheet, goalSheet, categorySheet, recurringSheet, levelUp]);
  const transactions = data.transactions[user.id] ?? [];
  const sortedTransactions = useMemo(() => [...transactions].sort((a, b) => new Date(b.date) - new Date(a.date)), [transactions]);
  const visibleTransactions = useMemo(() => {
    const byType = filter === 'all' ? sortedTransactions : sortedTransactions.filter((item) => item.type === filter);
    const byCategory = categoryFilter ? byType.filter((item) => item.category === categoryFilter) : byType;
    return sortMode === 'amount' ? [...byCategory].sort((a, b) => b.amount - a.amount) : byCategory;
  }, [sortedTransactions, filter, categoryFilter, sortMode]);
  const income = transactions.filter((item) => item.type === 'income').reduce((sum, item) => sum + item.amount, 0);
  const expense = transactions.filter((item) => item.type === 'expense').reduce((sum, item) => sum + item.amount, 0);
  const balance = income - expense;
  const goal = data.goals?.[user.id] ?? null;
  const achievements = data.achievements?.[user.id] ?? [];
  const goalReached = Boolean(goal && balance >= goal.amount);
  const budgets = data.budgets?.[user.id] ?? {};
  const categories = data.categories?.[user.id] ?? [];
  const recurrings = data.recurrings?.[user.id] ?? [];
  const expenseCategories = useMemo(() => categories.filter((item) => item.type !== 'income').map((item) => item.name), [categories]);
  const incomeCategories = useMemo(() => categories.filter((item) => item.type !== 'expense').map((item) => item.name), [categories]);
  const emojiMap = useMemo(() => Object.fromEntries(categories.map((item) => [item.name, item.emoji])), [categories]);
  const categoryChips = useMemo(() => {
    const counts = {};
    for (const item of transactions) if (item.category) counts[item.category] = (counts[item.category] ?? 0) + 1;
    return [...categories].sort((a, b) => ((counts[b.name] ?? 0) - (counts[a.name] ?? 0)) || a.name.localeCompare(b.name, 'id'));
  }, [categories, transactions]);
  const monthKey = today.slice(0, 7);
  const monthExpenses = transactions.filter((item) => item.type === 'expense' && item.date.startsWith(monthKey));
  const budgetEntries = Object.entries(budgets);
  const spendingFor = (category) => monthExpenses.filter((item) => item.category === category).reduce((sum, item) => sum + item.amount, 0);
  const categorySummary = expenseCategories.map((category) => ({ category, amount: spendingFor(category) })).filter((item) => item.amount > 0).sort((a, b) => b.amount - a.amount);
  const topSpending = categorySummary[0];
  const chartMax = topSpending?.amount || 1;
  const badgeViews = evaluateBadges(
    data.badgeDefs?.length ? data.badgeDefs : FALLBACK_BADGE_DEFS,
    badgeStats({ transactions, achievements, streakCurrent: user.streakCurrent, level: user.level }),
    new Set(data.badges?.[user.id] ?? []),
  );
  const unlockedBadges = badgeViews.filter((badge) => badge.unlocked).length;
  const topCardTier = ['legendary', 'epic', 'rare', 'common'].find((tier) => badgeViews.some((badge) => badge.unlocked && badge.rarity === tier)) ?? 'common';
  const canShareCard = typeof navigator !== 'undefined' && Boolean(navigator.canShare);
  const profInfo = levelProgress(user.xp ?? 0);

  useEffect(() => {
    const owned = new Set(data.badges?.[user.id] ?? []);
    const fresh = badgeViews.filter((badge) => badge.unlocked && !owned.has(badge.code));
    if (!fresh.length) return;
    supabase.from('user_badges').insert(fresh.map((badge) => ({ user_id: user.id, badge_code: badge.code }))).then(({ error }) => {
      if (error) return;
      setData((current) => ({ ...current, badges: { ...current.badges, [user.id]: [...(current.badges[user.id] ?? []), ...fresh.map((badge) => badge.code)] } }));
    });
  }, [badgeViews]);

  async function addTransaction(transaction) {
    const xpEarned = hitungXpEarned(transaction, transactions, budgets);
    const previousLevel = user.level ?? 1;
    const totalXp = (user.xp ?? 0) + xpEarned;
    const newLevel = levelFromXp(totalXp);
    const { data: inserted, error } = await supabase
      .from('transactions')
      .insert({ user_id: user.id, type: transaction.type, title: transaction.title, amount: transaction.amount, category: transaction.category, date: transaction.date, xp_earned: xpEarned })
      .select()
      .single();
    if (error || !inserted) return false;
    let streakInfo = null;
    try {
      const { data: prof } = await supabase.from('profiles').select('streak_current, streak_longest, last_activity_date').eq('id', user.id).single();
      streakInfo = nextStreak(prof?.last_activity_date, prof?.streak_current, prof?.streak_longest);
      await supabase.from('profiles').update({ streak_current: streakInfo.streakCurrent, streak_longest: streakInfo.streakLongest, last_activity_date: streakInfo.today }).eq('id', user.id);
    } catch {
      streakInfo = null;
    }
    setData((current) => ({
      ...current,
      transactions: { ...current.transactions, [user.id]: [mapTransaction(inserted), ...(current.transactions[user.id] ?? [])] },
      users: current.users.map((item) => (item.id === user.id ? { ...item, xp: totalXp, level: newLevel, ...(streakInfo ? { streakCurrent: streakInfo.streakCurrent, streakLongest: streakInfo.streakLongest } : {}) } : item)),
    }));
    setShowForm(false);
    if (newLevel > previousLevel) setLevelUp({ level: newLevel, title: titleForLevel(newLevel), xpEarned });
    return true;
  }
  async function removeTransaction(id) {
    const { error } = await supabase.from('transactions').delete().eq('id', id);
    if (error) return;
    setData((current) => ({ ...current, transactions: { ...current.transactions, [user.id]: (current.transactions[user.id] ?? []).filter((item) => item.id !== id) } }));
  }
  async function logout() {
    await supabase.auth.signOut();
    setData((current) => ({ ...current, activeUserId: null }));
  }
  async function buildCardBlob() {
    const canvas = await drawProfileCard({ username: user.username, level: user.level ?? 1, levelTitle: titleForLevel(user.level ?? 1), streak: user.streakCurrent ?? 0, badgesUnlocked: unlockedBadges, badgesTotal: badgeViews.length, tier: topCardTier });
    return new Promise((resolve) => canvas.toBlob(resolve, 'image/png'));
  }
  async function downloadProfileCard() {
    const blob = await buildCardBlob();
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `rapi-kartu-${user.username}.png`;
    link.click();
    URL.revokeObjectURL(url);
  }
  async function shareProfileCard() {
    const blob = await buildCardBlob();
    const file = new File([blob], `rapi-kartu-${user.username}.png`, { type: 'image/png' });
    if (navigator.canShare?.({ files: [file] })) {
      try { await navigator.share({ files: [file], title: 'Kartu pencapaianku di rapi ✨' }); } catch {}
    } else {
      await downloadProfileCard();
    }
  }
  async function saveGoal(name, amount) {
    const existing = await supabase.from('goals').select('id').eq('user_id', user.id).eq('is_active', true).maybeSingle();
    if (existing.data) await supabase.from('goals').update({ name: name.trim(), amount }).eq('id', existing.data.id);
    else await supabase.from('goals').insert({ user_id: user.id, name: name.trim(), amount });
    setData((current) => ({ ...current, goals: { ...current.goals, [user.id]: { name: name.trim(), amount } } }));
    return true;
  }
  async function saveBudget(category, amount) {
    const { error } = await supabase.from('budgets').upsert({ user_id: user.id, category, monthly_limit: amount });
    if (error) return false;
    setData((current) => ({ ...current, budgets: { ...current.budgets, [user.id]: { ...(current.budgets?.[user.id] ?? {}), [category]: amount } } }));
    return true;
  }
  async function saveCategory({ name, emoji, type }) {
    const cleanName = name.trim();
    const cleanEmoji = Array.from(emoji.trim())[0] ?? '';
    if (!cleanEmoji) return false;
    const { data: row, error } = await supabase.from('categories')
      .upsert({ user_id: user.id, name: cleanName, emoji: cleanEmoji, type }, { onConflict: 'user_id,name' })
      .select()
      .single();
    if (error || !row) return false;
    setData((current) => ({
      ...current,
      categories: { ...current.categories, [user.id]: [...(current.categories[user.id] ?? []).filter((item) => item.name !== cleanName), mapCategory(row)] },
    }));
    return true;
  }
  async function removeCategory(id) {
    const target = (data.categories?.[user.id] ?? []).find((item) => item.id === id);
    if (!target || target.isDefault) return false;
    const { error } = await supabase.from('categories').delete().eq('id', id);
    if (error) return false;
    setData((current) => ({ ...current, categories: { ...current.categories, [user.id]: (current.categories[user.id] ?? []).filter((item) => item.id !== id) } }));
    return true;
  }
  async function addRecurring(payload) {
    const tomorrow = addDays(today, 1);
    const nextRun = occurrenceOnOrAfter({ frequency: payload.frequency, dayOfPeriod: payload.dayOfPeriod }, payload.startDate > tomorrow ? payload.startDate : tomorrow);
    const { data: row, error } = await supabase.from('recurring_transactions')
      .insert({ user_id: user.id, type: payload.type, title: payload.title, amount: payload.amount, category: payload.category, frequency: payload.frequency, day_of_period: payload.dayOfPeriod, next_run_date: nextRun })
      .select()
      .single();
    if (error || !row) return false;
    setData((current) => ({ ...current, recurrings: { ...current.recurrings, [user.id]: [...(current.recurrings?.[user.id] ?? []), mapRecurring(row)] } }));
    return true;
  }
  async function removeRecurring(id) {
    const { error } = await supabase.from('recurring_transactions').delete().eq('id', id);
    if (error) return false;
    setData((current) => ({ ...current, recurrings: { ...current.recurrings, [user.id]: (current.recurrings[user.id] ?? []).filter((item) => item.id !== id) } }));
    return true;
  }
  function setReminderPref(key, value) {
    try { window.localStorage.setItem(key, value); } catch {}
  }
  async function toggleReminders(next) {
    setReminderMsg('');
    if (!next) {
      setReminderEnabled(false);
      setReminderPref('rapi.reminder.enabled', '0');
      syncReminders({ enabled: false });
      return;
    }
    let state = await reminderPermissionState();
    if (state !== 'granted') state = await requestReminderPermission();
    if (state !== 'granted') return setReminderMsg('Izin notifikasi ditolak. Aktifkan dari pengaturan sistem ya.');
    setReminderEnabled(true);
    setReminderPref('rapi.reminder.enabled', '1');
    const ok = await syncReminders({ enabled: true, hour: reminderHour, recurrings });
    if (!ok) return setReminderMsg('Gagal menjadwalkan pengingat. Coba lagi ya.');
    await fireTestPing();
    setReminderMsg('Pengingat aktif! Tes dikirim 15 detik dari sekarang 📳');
  }
  async function changeReminderHour(value) {
    const hour = Number(value);
    setReminderHour(hour);
    setReminderPref('rapi.reminder.hour', String(hour));
    if (reminderEnabled) await syncReminders({ enabled: true, hour, recurrings });
  }
  async function claimGoal() {
    if (!goalReached || !window.confirm(`Klaim pencapaian “${goal.name}”? Kamu bisa membuat wishlist baru setelahnya.`)) return;
    await supabase.from('achievements').insert({ user_id: user.id, goal_name: goal.name, goal_amount: goal.amount, completed_at: today });
    await supabase.from('goals').update({ is_active: false }).eq('user_id', user.id).eq('is_active', true);
    setData((current) => ({ ...current, goals: { ...current.goals, [user.id]: null }, achievements: { ...current.achievements, [user.id]: [...(current.achievements?.[user.id] ?? []), { ...goal, id: crypto.randomUUID(), completedAt: today }] } }));
  }
  async function deleteAccount() {
    if (!window.confirm(`Hapus akun ${user.username} beserta seluruh catatan keuangannya? Tindakan ini tidak dapat dibatalkan.`)) return;
    await supabase.from('profiles').delete().eq('id', user.id);
    await supabase.auth.signOut();
    setData((current) => {
      const nextTransactions = { ...current.transactions };
      delete nextTransactions[user.id];
      const nextGoals = { ...current.goals }; delete nextGoals[user.id];
      const nextAchievements = { ...current.achievements }; delete nextAchievements[user.id];
      const nextBudgets = { ...current.budgets }; delete nextBudgets[user.id];
      return { users: current.users.filter((item) => item.id !== user.id), transactions: nextTransactions, goals: nextGoals, achievements: nextAchievements, budgets: nextBudgets, activeUserId: null };
    });
  }

  return <main className="dashboard-page">
    <div className="dashboard app-frame" id="dashboard">
      {tab === 'beranda' && <>
      <header className="mobile-header"><a className="brand dark brutal-brand" href="#dashboard"><span>r</span> rapi</a></header>
      <section className="dashboard-heading clay-heading brutal-heading">
        <div><p className="kicker">RINGKASAN KEUANGAN</p><h1>Halo, {user.username}. <em>Bagaimana harimu?</em></h1><p className="subline">Semua catatanmu ada di satu tempat.</p></div>
        <button className="clay-button brutal-button" onClick={() => setShowForm(true)}><span>+</span> Catat transaksi</button>
      </section>
      <section className="summary-grid">
        <BalanceCard balance={balance} hidden={hideBalance} onToggleHidden={toggleHideBalance} xp={user.xp ?? 0} streak={user.streakCurrent ?? 0} />
        <StatCard label="Pemasukan" amount={income} icon="↓" variant="income" hidden={hideBalance} />
        <StatCard label="Pengeluaran" amount={expense} icon="↑" variant="expense" hidden={hideBalance} />
      </section>
      </>}
      {tab === 'target' && <>
      <section className="playful-grid tab-target">
        <article className={`goal-card clay-card clay-goal brutal-card brutal-goal ${goalReached ? 'goal-reached' : ''}`}><div><p className="kicker">{goalReached ? 'WISHLIST TERCAPAI! 🎉' : 'TARGET TABUNGAN'}</p><h2>{goal ? goal.name : 'Punya wishlist?'}</h2>{goal ? <><div className="goal-progress"><span style={{ width: `${Math.min(100, Math.max(0, balance / goal.amount * 100))}%` }} /></div><p className="goal-caption"><strong>{rupiah.format(Math.max(0, balance))}</strong> dari {rupiah.format(goal.amount)}</p></> : <p className="goal-caption">Buat target kecil agar menabung terasa lebih seru.</p>}</div>{goalReached ? <button className="claim-goal clay-button brutal-button brutal-success" onClick={claimGoal}>Klaim badge 🏆</button> : <button className="goal-button clay-button brutal-button" onClick={() => setGoalSheet(true)}>{goal ? 'Ubah target' : '+ Buat target'}</button>}</article>
        <article className="badge-card clay-card clay-badge brutal-card brutal-badge"><div className="badge-heading"><div><p className="kicker">KOLEKSI BADGE</p><h2>Good job, bestie! ✨</h2></div><span>{unlockedBadges}/{badgeViews.length}</span></div><div className="badges">{badgeViews.map((badge) => <div className={`badge tier-${badge.rarity} ${badge.unlocked ? 'unlocked' : 'locked'}`} key={badge.code}><span>{badge.icon}</span><div><strong>{badge.title}</strong><small>{badge.unlocked ? badge.note : `${Math.min(badge.current, badge.target)}/${badge.target} · ${badge.note}`}</small>{!badge.unlocked && <i className="badge-progress"><em style={{ width: `${badge.progress * 100}%` }} /></i>}</div><b className="badge-tier">{badge.rarity}</b></div>)}</div></article>
      </section>
      </>}
      {tab === 'beranda' && <>
      <section className="insight-section clay-insight brutal-section"><div className="section-header"><div><h2>Money check-in</h2><p>Snapshot bulan ini, bestie 💫</p></div></div><div className="insight-grid"><article className="insight-card clay-card brutal-card"><span>💡</span><div><p className="kicker">{topSpending ? 'Paling banyak di sini' : 'Money check-in'}</p><strong>{topSpending ? `${emojiMap[topSpending.category] ?? '✨'} ${topSpending.category}` : 'Belum ada pengeluaran'}</strong>{topSpending && <span className="insight-amount">{rupiah.format(topSpending.amount)}</span>}<p className="insight-caption">{topSpending ? 'Terpakai untuk kategori ini sejauh ini.' : 'Mulai catat transaksi untuk melihat insight personal.'}</p></div></article><article className="chart-card clay-card brutal-card"><div className="chart-title"><strong>Pengeluaran per kategori</strong><span>Bulan ini</span></div>{categorySummary.length ? <div className="chart-bars">{categorySummary.map((item) => <div className="chart-row" key={item.category}><span>{emojiMap[item.category] ?? '✨'}</span><div><div><strong>{item.category}</strong><b>{rupiah.format(item.amount)}</b></div><i><em style={{ width: `${item.amount / chartMax * 100}%` }} /></i></div></div>)}</div> : <p className="chart-empty">Grafik akan muncul setelah ada pengeluaran.</p>}</article></div></section>
      <section className="budget-section clay-budget brutal-section"><div className="section-header"><div><h2>Budget bulan ini</h2><p>Jaga pengeluaran tetap on track ✨</p></div><button className="budget-add clay-button brutal-button" onClick={() => setBudgetSheet({})}>+ Atur budget</button></div>{budgetEntries.length ? <div className="budget-grid">{budgetEntries.map(([category, limit]) => { const spent = spendingFor(category); const ratio = spent / limit; const state = ratio >= 1 ? 'over' : ratio >= .8 ? 'near' : 'safe'; return <article className="budget-item clay-card brutal-card" key={category}><div><span>{emojiMap[category] ?? '✨'}</span><strong>{category}</strong><button onClick={() => setBudgetSheet({ category })} aria-label={`Ubah budget ${category}`}>⋯</button></div><div className="budget-bar"><span className={state} style={{ width: `${Math.min(100, ratio * 100)}%` }} /></div><p><b>{rupiah.format(spent)}</b> / {rupiah.format(limit)} <em>{state === 'over' ? 'Kelebihan!' : state === 'near' ? 'Hampir habis' : 'Aman'}</em></p></article>; })}</div> : <div className="budget-empty brutal-empty"><span>🪄</span><div><strong>Belum ada budget</strong><p>Tentukan batas pengeluaran untuk kategori favoritmu.</p></div><button className="clay-button brutal-button" onClick={() => setBudgetSheet({})}>Buat budget</button></div>}</section>
      </>}
      {tab === 'transaksi' && <>
      <section className="transactions-section clay-transactions brutal-section">
        <div className="section-header"><div><h2>Riwayat transaksi</h2><p>{transactions.length} transaksi tercatat</p></div><div className="filters brutal-filters">{[['all', 'Semua'], ['income', 'Masuk'], ['expense', 'Keluar']].map(([id, label]) => <button key={id} className={filter === id ? 'active' : ''} onClick={() => setFilter(id)}>{label}</button>)}</div></div>
        <div className="list-toolbar">
          <div className="category-filters" role="group" aria-label="Filter kategori">
            {categoryChips.map((item) => <button key={item.id} type="button" className={categoryFilter === item.name ? 'active' : ''} aria-pressed={categoryFilter === item.name} onClick={() => setCategoryFilter(categoryFilter === item.name ? '' : item.name)}>{item.emoji} {item.name}</button>)}
          </div>
          <div className="sort-toggle" role="group" aria-label="Urutkan transaksi">
            <button type="button" className={sortMode === 'newest' ? 'active' : ''} onClick={() => setSortMode('newest')}>Terbaru</button>
            <button type="button" className={sortMode === 'amount' ? 'active' : ''} onClick={() => setSortMode('amount')}>Terbesar</button>
          </div>
        </div>
        <div className="transaction-list">
          {visibleTransactions.length ? visibleTransactions.map((item) => <Transaction key={item.id} item={item} emojiMap={emojiMap} onDelete={removeTransaction} />) : <EmptyState filter={filter} filtered={filter !== 'all' || Boolean(categoryFilter)} onAdd={() => setShowForm(true)} />}
        </div>
      </section>
      </>}
      {tab === 'profil' && <section className="profil-stack">
      <div className="profile-head"><span className="avatar big">{user.username.slice(0, 1).toUpperCase()}</span><div><strong>{user.username}</strong><small>Lv {profInfo.level} · {titleForLevel(user.level ?? 1)}</small></div></div>
      <article className="share-card clay-card brutal-card brutal-share"><p className="kicker">KARTU PROFIL</p><h2>Flex pencapaianmu ✨</h2><p className="share-note">Generate kartu berisi level, streak, dan badge buat dibagikan ke story.</p><div className="card-actions"><button className="card-button clay-button brutal-button" onClick={downloadProfileCard}>🖼️ Unduh kartu</button>{canShareCard && <button className="card-button ghost-button clay-button brutal-button brutal-ghost" onClick={shareProfileCard}>Bagikan</button>}</div></article>
      <section className="manage-categories brutal-section">
        <div className="section-header"><div><p className="kicker">KATEGORI</p><h2>Kelola kategori</h2></div><button className="clay-button brutal-button" onClick={() => setCategorySheet(true)}>+ Kategori</button></div>
        <article className="category-manage-card brutal-card">
          <CategoryRows label="Pemasukan" items={categories.filter((item) => item.type !== 'expense')} onDelete={removeCategory} />
          <CategoryRows label="Pengeluaran" items={categories.filter((item) => item.type !== 'income')} onDelete={removeCategory} />
        </article>
      </section>
      <section className="manage-recurring brutal-section">
        <div className="section-header"><div><p className="kicker">TRANSAKSI BERULANG</p><h2>Langganan & tagihan rutin</h2></div><button className="clay-button brutal-button" onClick={() => setRecurringSheet(true)}>+ Rutin</button></div>
        <article className="brutal-card recurring-manage-card">
          {recurrings.length ? recurrings.map((rule) => <div className="recurring-row" key={rule.id}>
            <span className="category-emoji">{emojiMap[rule.category] ?? '🔁'}</span>
            <div className="recurring-info">
              <strong>{rule.title}</strong>
              <small>{rupiah.format(rule.amount)} · {rule.frequency === 'monthly' ? `tiap bulan tgl ${rule.dayOfPeriod}` : `tiap ${WEEKDAY_LABELS[rule.dayOfPeriod] ?? 'mingguan'}`}</small>
              <small className="muted">Berikutnya: {dateFormatter.format(new Date(`${rule.nextRunDate}T00:00:00`))}</small>
            </div>
            <button type="button" aria-label={`Hapus ${rule.title}`} onClick={() => removeRecurring(rule.id)}>×</button>
          </div>          ) : <p className="recurring-empty">Belum ada biaya rutin. Tambahkan kayak kos, Netflix, atau gaji bulanan.</p>}
        </article>
      </section>
      {showReminderCard && <section className="manage-reminders brutal-section">
        <div className="section-header"><div><p className="kicker">PENGINGAT</p><h2>Jangan putus streak</h2></div></div>
        <article className="brutal-card reminder-card">
          <div className="reminder-row">
            <div><strong>Aktifkan pengingat</strong><p>Catat transaksi tiap malam + tagihan rutin jatuh tempo.</p></div>
            <button type="button" role="switch" aria-checked={reminderEnabled} aria-label="Aktifkan pengingat" className={`reminder-toggle ${reminderEnabled ? 'on' : ''}`} onClick={() => toggleReminders(!reminderEnabled)}><i /></button>
          </div>
          {reminderEnabled && <>
            <label className="reminder-hour">Jam pengingat<select value={reminderHour} onChange={(e) => changeReminderHour(e.target.value)}>{[18, 19, 20, 21].map((h) => <option key={h} value={h}>{`${h}:00`}</option>)}</select></label>
            <button type="button" className="clay-button brutal-button brutal-ghost reminder-test" onClick={() => fireTestPing()}>Tes notifikasi (15 dtk)</button>
          </>}
          {reminderMsg && <p className="form-message">{reminderMsg}</p>}
        </article>
      </section>}
      <section className="danger-zone clay-danger brutal-danger"><div><strong>Hapus akun</strong><p>Seluruh transaksi pada akun ini akan dihapus permanen dari perangkat.</p></div><button className="danger-button clay-button brutal-button brutal-danger-btn" onClick={deleteAccount}>Hapus akun</button></section>
      <button className="logout-full clay-button brutal-button brutal-ghost" onClick={logout}>Keluar dari akun</button>
      </section>}
    </div>
    {toast && <div className="brutal-toast" role="status">{toast}</div>}
    <BottomNav active={tab} onChange={setTab} onAdd={() => setShowForm(true)} />
    {showForm && <TransactionForm expenseOptions={expenseCategories} incomeOptions={incomeCategories} onClose={() => setShowForm(false)} onSubmit={addTransaction} />}
    {budgetSheet && <BudgetSheet options={expenseCategories} initialCategory={budgetSheet.category ?? ''} currentLimit={budgetSheet.category ? budgets[budgetSheet.category] : ''} onClose={() => setBudgetSheet(null)} onSubmit={saveBudget} />}
    {goalSheet && <GoalSheet goal={goal} onClose={() => setGoalSheet(false)} onSubmit={saveGoal} />}
    {categorySheet && <CategorySheet existingNames={categories.map((item) => item.name)} onClose={() => setCategorySheet(false)} onSubmit={saveCategory} />}
    {recurringSheet && <RecurringSheet categories={categories} onClose={() => setRecurringSheet(false)} onSubmit={addRecurring} />}
    {levelUp && <LevelUpModal {...levelUp} onClose={() => setLevelUp(null)} />}
  </main>;
}

function BalanceCard({ balance, hidden = false, onToggleHidden, xp, streak = 0 }) {
  const info = levelProgress(xp);
  return <article className="balance-card clay-card brutal-card"><div><div className="balance-label-row"><p>Saldo saat ini</p><button type="button" className="eye-toggle" aria-pressed={hidden} aria-label={hidden ? 'Tampilkan saldo' : 'Sembunyikan saldo'} onClick={onToggleHidden}>{hidden ? '🙈' : '👁️'}</button></div><strong>{hidden ? MASKED_AMOUNT : rupiah.format(balance)}</strong><small>{balance >= 0 ? 'Keuanganmu terlihat terjaga.' : 'Pengeluaran melebihi pemasukan.'}</small><div className="level-strip"><div className="level-chip"><b>Lv {info.level}</b><span>{info.title}</span></div><div className="level-bar" role="progressbar" aria-valuenow={info.percent} aria-valuemin={0} aria-valuemax={100} aria-label={`Progress XP menuju level ${info.level + 1}`}><span style={{ width: `${info.percent}%` }} /></div><small>{info.xpIntoLevel}/{info.xpForNextLevel} XP menuju Lv {info.level + 1}</small><div className={`streak-chip ${streak > 0 ? 'active' : 'idle'}`}>{streak > 0 ? `🔥 ${streak} hari beruntun` : 'Mulai streak-mu hari ini!'}</div></div></div><div className="balance-mark">Rp</div></article>;
}
function StatCard({ label, amount, icon, variant, hidden = false }) { return <article className={`stat-card clay-card brutal-card ${variant}`}><span className={`stat-icon ${variant}`}>{icon}</span><div><p>{label}</p><strong>{hidden ? MASKED_AMOUNT : rupiah.format(amount)}</strong><small>{variant === 'income' ? 'Total uang masuk' : 'Total uang keluar'}</small></div></article>; }

function Transaction({ item, emojiMap = {}, onDelete }) {
  const income = item.type === 'income';
  return <article className="transaction clay-card brutal-card brutal-row"><span className={`transaction-icon ${income ? 'income' : 'expense'}`}>{emojiMap[item.category] || '✨'}</span><div className="transaction-info"><strong>{item.title}</strong><span>{item.category} <i>•</i> {dateFormatter.format(new Date(`${item.date}T00:00:00`))}</span></div><strong className={income ? 'amount income-text' : 'amount expense-text'}>{income ? '+' : '−'} {rupiah.format(item.amount)}</strong><button className="delete-transaction" aria-label={`Hapus ${item.title}`} onClick={() => onDelete(item.id)}>×</button></article>;
}

function EmptyState({ filter, filtered = false, onAdd }) { return <div className="empty brutal-empty-state"><span>⌁</span><h3>{filtered ? 'Tidak ada yang cocok' : filter === 'all' ? 'Belum ada transaksi' : 'Tidak ada transaksi di sini'}</h3><p>{filtered ? 'Coba longgarkan filter kategori atau tipenya ya.' : 'Mulai catat pemasukan atau pengeluaran pertamamu.'}</p>{filter === 'all' && !filtered && <button className="empty-button clay-button brutal-button" onClick={onAdd}>Catat transaksi</button>}</div>; }

function TransactionForm({ expenseOptions = [], incomeOptions = [], onClose, onSubmit }) {
  const [type, setType] = useState('expense');
  const [title, setTitle] = useState('');
  const [amount, setAmount] = useState('');
  const [category, setCategory] = useState('');
  const [date, setDate] = useState(today);
  const [message, setMessage] = useState('');
  const categories = type === 'income' ? incomeOptions : expenseOptions;
  async function submit(event) {
    event.preventDefault();
    const numericAmount = Number(amount);
    if (!title.trim() || !category || !date || !Number.isFinite(numericAmount) || numericAmount <= 0) return setMessage('Lengkapi semua data transaksi dengan benar.');
    const saved = await onSubmit({ title: title.trim(), amount: numericAmount, category, date, type });
    if (!saved) setMessage('Transaksi gagal tersimpan. Coba lagi ya.');
  }
  return <div className="modal-backdrop clay-modal brutal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal clay-card brutal-sheet" role="dialog" aria-modal="true" aria-labelledby="form-title" onMouseDown={(event) => event.stopPropagation()}><button className="close-modal" onClick={onClose} aria-label="Tutup">×</button><p className="kicker">TRANSAKSI BARU</p><h2 id="form-title">Catat aktivitas keuangan</h2><form onSubmit={submit}><div className="type-switch"><button type="button" className={type === 'expense' ? 'selected expense' : ''} onClick={() => { setType('expense'); setCategory(''); }}>Pengeluaran</button><button type="button" className={type === 'income' ? 'selected income' : ''} onClick={() => { setType('income'); setCategory(''); }}>Pemasukan</button></div><label>Nama transaksi<input autoFocus value={title} onChange={(e) => setTitle(e.target.value)} placeholder={type === 'income' ? 'Contoh: Gaji bulanan' : 'Contoh: Makan siang'} /></label><label>Nominal<input inputMode="numeric" value={amount} onChange={(e) => setAmount(e.target.value.replace(/[^0-9]/g, ''))} placeholder="Contoh: 50000" /></label><div className="form-pair"><label>Kategori<select value={category} onChange={(e) => setCategory(e.target.value)}><option value="">Pilih kategori</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label>Tanggal<input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label></div>{message && <p className="form-message">{message}</p>}<div className="form-actions"><button className="ghost-button clay-button brutal-button brutal-ghost" type="button" onClick={onClose}>Batal</button><button className="primary-button clay-button brutal-button" type="submit">Simpan transaksi <span>→</span></button></div></form></section></div>;
}

function BudgetSheet({ options = [], initialCategory = '', currentLimit = '', onClose, onSubmit }) {
  const [category, setCategory] = useState(initialCategory);
  const [amount, setAmount] = useState(currentLimit ? String(currentLimit) : '');
  const [message, setMessage] = useState('');
  async function submit(event) {
    event.preventDefault();
    const numericAmount = Number(amount);
    if (!category || !options.includes(category)) return setMessage('Pilih kategori terlebih dahulu.');
    if (!Number.isFinite(numericAmount) || numericAmount <= 0) return setMessage('Masukkan nominal limit yang benar.');
    if (!(await onSubmit(category, numericAmount))) return setMessage('Budget gagal disimpan. Coba lagi ya.');
    onClose();
  }
  return <div className="modal-backdrop clay-modal brutal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal clay-card brutal-sheet" role="dialog" aria-modal="true" aria-labelledby="budget-title" onMouseDown={(event) => event.stopPropagation()}><button className="close-modal" onClick={onClose} aria-label="Tutup">×</button><p className="kicker">BUDGET BULANAN</p><h2 id="budget-title">{initialCategory ? 'Ubah limit budget' : 'Atur limit budget'}</h2><form onSubmit={submit}><label>Kategori<select value={category} onChange={(e) => setCategory(e.target.value)}><option value="">Pilih kategori</option>{options.map((item) => <option key={item}>{item}</option>)}</select></label><label>Limit bulanan<input inputMode="numeric" value={amount} onChange={(e) => setAmount(e.target.value.replace(/[^0-9]/g, ''))} placeholder="Contoh: 750000" /></label>{message && <p className="form-message">{message}</p>}<div className="form-actions"><button className="ghost-button clay-button brutal-button brutal-ghost" type="button" onClick={onClose}>Batal</button><button className="primary-button clay-button brutal-button" type="submit">Simpan budget <span>→</span></button></div></form></section></div>;
}

function GoalSheet({ goal, onClose, onSubmit }) {
  const [name, setName] = useState(goal?.name ?? '');
  const [amount, setAmount] = useState(goal?.amount ? String(goal.amount) : '');
  const [message, setMessage] = useState('');
  async function submit(event) {
    event.preventDefault();
    const numericAmount = Number(amount);
    if (!name.trim()) return setMessage('Beri nama target impianmu dulu.');
    if (!Number.isFinite(numericAmount) || numericAmount <= 0) return setMessage('Masukkan nominal target yang benar.');
    if (!(await onSubmit(name.trim(), numericAmount))) return setMessage('Target gagal disimpan. Coba lagi ya.');
    onClose();
  }
  return <div className="modal-backdrop clay-modal brutal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal clay-card brutal-sheet" role="dialog" aria-modal="true" aria-labelledby="goal-title" onMouseDown={(event) => event.stopPropagation()}><button className="close-modal" onClick={onClose} aria-label="Tutup">×</button><p className="kicker">TARGET TABUNGAN</p><h2 id="goal-title">{goal ? 'Ubah wishlist' : 'Buat wishlist baru'}</h2><form onSubmit={submit}><label>Nama target<input value={name} onChange={(e) => setName(e.target.value)} placeholder="Contoh: Dana impian" /></label><label>Nominal target<input inputMode="numeric" value={amount} onChange={(e) => setAmount(e.target.value.replace(/[^0-9]/g, ''))} placeholder="Contoh: 5000000" /></label>{message && <p className="form-message">{message}</p>}<div className="form-actions"><button className="ghost-button clay-button brutal-button brutal-ghost" type="button" onClick={onClose}>Batal</button><button className="primary-button clay-button brutal-button" type="submit">Simpan target <span>→</span></button></div></form></section></div>;
}

function CategoryRows({ label, items, onDelete }) {
  return <div className="category-group">
    <small>{label}</small>
    {items.map((item) => <div className="category-row" key={item.id}>
      <span className="category-emoji">{item.emoji}</span>
      <strong>{item.name}</strong>
      {item.isDefault && <em>default</em>}
      {!item.isDefault && <button type="button" aria-label={`Hapus kategori ${item.name}`} onClick={() => onDelete(item.id)}>×</button>}
    </div>)}
  </div>;
}

function CategorySheet({ existingNames = [], onClose, onSubmit }) {
  const [type, setType] = useState('expense');
  const [emoji, setEmoji] = useState('');
  const [name, setName] = useState('');
  const [message, setMessage] = useState('');
  async function submit(event) {
    event.preventDefault();
    const cleanName = name.trim();
    const cleanEmoji = Array.from(emoji.trim())[0] ?? '';
    if (!cleanName) return setMessage('Beri nama kategorinya dulu.');
    if (existingNames.some((item) => item.toLowerCase() === cleanName.toLowerCase())) return setMessage('Kategori dengan nama itu sudah ada.');
    if (!cleanEmoji) return setMessage('Pilih satu emoji untuk kategorimu.');
    if (!(await onSubmit({ name: cleanName, emoji: cleanEmoji, type }))) return setMessage('Kategori gagal disimpan. Coba lagi ya.');
    onClose();
  }
  return <div className="modal-backdrop clay-modal brutal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal clay-card brutal-sheet" role="dialog" aria-modal="true" aria-labelledby="category-title" onMouseDown={(event) => event.stopPropagation()}><button className="close-modal" onClick={onClose} aria-label="Tutup">×</button><p className="kicker">KATEGORI BARU</p><h2 id="category-title">Tambah kategori</h2><form onSubmit={submit}><div className="type-switch"><button type="button" className={type === 'expense' ? 'selected expense' : ''} onClick={() => setType('expense')}>Pengeluaran</button><button type="button" className={type === 'income' ? 'selected income' : ''} onClick={() => setType('income')}>Pemasukan</button><button type="button" className={type === 'both' ? 'selected both' : ''} onClick={() => setType('both')}>Keduanya</button></div><label>Nama kategori<input value={name} onChange={(e) => setName(e.target.value)} maxLength={24} placeholder="Contoh: Jajan bubble" /></label><label>Emoji<div className="emoji-field"><span>{Array.from(emoji.trim())[0] || '❓'}</span><input value={emoji} onChange={(e) => setEmoji(e.target.value)} maxLength={8} placeholder="📦" /></div></label>{message && <p className="form-message">{message}</p>}<div className="form-actions"><button className="ghost-button clay-button brutal-button brutal-ghost" type="button" onClick={onClose}>Batal</button><button className="primary-button clay-button brutal-button" type="submit">Simpan kategori <span>→</span></button></div></form></section></div>;
}

function RecurringSheet({ categories = [], onClose, onSubmit }) {
  const [type, setType] = useState('expense');
  const [title, setTitle] = useState('');
  const [amount, setAmount] = useState('');
  const [frequency, setFrequency] = useState('monthly');
  const [dayOfPeriod, setDayOfPeriod] = useState('');
  const [category, setCategory] = useState('');
  const [startDate, setStartDate] = useState(today);
  const [message, setMessage] = useState('');
  const options = categories.filter((item) => item.type === type || item.type === 'both');
  async function submit(event) {
    event.preventDefault();
    const numericAmount = Number(amount);
    if (!title.trim()) return setMessage('Beri nama langganan atau tagihannya dulu.');
    if (!Number.isFinite(numericAmount) || numericAmount <= 0) return setMessage('Masukkan nominal yang benar.');
    if (!category) return setMessage('Pilih kategori terlebih dahulu.');
    if (!dayOfPeriod) return setMessage(frequency === 'monthly' ? 'Pilih tanggal penagihan.' : 'Pilih hari penagihan.');
    if (!startDate) return setMessage('Pilih tanggal mulai.');
    if (!(await onSubmit({ type, title: title.trim(), amount: numericAmount, category, frequency, dayOfPeriod: Number(dayOfPeriod), startDate }))) return setMessage('Transaksi rutin gagal disimpan. Coba lagi ya.');
    onClose();
  }
  return <div className="modal-backdrop clay-modal brutal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal clay-card brutal-sheet" role="dialog" aria-modal="true" aria-labelledby="recurring-title" onMouseDown={(event) => event.stopPropagation()}><button className="close-modal" onClick={onClose} aria-label="Tutup">×</button><p className="kicker">TRANSAKSI BERULANG</p><h2 id="recurring-title">Tambah biaya rutin</h2><form onSubmit={submit}><div className="type-switch"><button type="button" className={type === 'expense' ? 'selected expense' : ''} onClick={() => { setType('expense'); setCategory(''); }}>Pengeluaran</button><button type="button" className={type === 'income' ? 'selected income' : ''} onClick={() => { setType('income'); setCategory(''); }}>Pemasukan</button></div><label>Nama<input value={title} onChange={(e) => setTitle(e.target.value)} maxLength={30} placeholder="Contoh: Netflix" /></label><label>Nominal<input inputMode="numeric" value={amount} onChange={(e) => setAmount(e.target.value.replace(/[^0-9]/g, ''))} placeholder="Contoh: 54000" /></label><div className="form-pair"><label>Frekuensi<select value={frequency} onChange={(e) => { setFrequency(e.target.value); setDayOfPeriod(''); }}><option value="monthly">Bulanan</option><option value="weekly">Mingguan</option></select></label><label>Kategori<select value={category} onChange={(e) => setCategory(e.target.value)}><option value="">Pilih kategori</option>{options.map((item) => <option key={item.name}>{item.name}</option>)}</select></label></div>{frequency === 'monthly' ? <label>Tanggal penagihan<select value={dayOfPeriod} onChange={(e) => setDayOfPeriod(e.target.value)}><option value="">Pilih tanggal</option>{Array.from({ length: 28 }, (_, i) => i + 1).map((d) => <option key={d} value={d}>{`tgl ${d}`}</option>)}</select></label> : <label>Hari penagihan<div className="weekday-chips">{[1, 2, 3, 4, 5, 6, 7].map((d) => <button type="button" key={d} className={String(dayOfPeriod) === String(d) ? 'selected' : ''} onClick={() => setDayOfPeriod(String(d))}>{['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'][d - 1]}</button>)}</div></label>}<label>Mulai tanggal<input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} /></label>{message && <p className="form-message">{message}</p>}<div className="form-actions"><button className="ghost-button clay-button brutal-button brutal-ghost" type="button" onClick={onClose}>Batal</button><button className="primary-button clay-button brutal-button" type="submit">Simpan rutin <span>→</span></button></div></form></section></div>;
}
